### ISSUE TITLE
icons disappear when exporting to pdf 

### ISSUE THREAD

**Issue by dany52** [valentine195/obsidian-admonition#1]
[obsidian-admonition pdf bug.pdf](https://github.com/valentine195/obsidian-admonition/files/6229675/obsidian-admonition.pdf.bug.pdf)

**Comment by valentine195** [comment]
Are you talking about the icons next to the title? Because I see it in the pdf you uploaded:

![image](https://user-images.githubusercontent.com/38669521/113004905-f8eb3d00-9141-11eb-86bb-27735602e95c.png)

**Comment by dany52** [comment]
Hmm... You are right! Everything is fine with pdf. It's Xreader 1.8.5 issue. The pdf is displayed normally in Okular.
