### ISSUE TITLE
"Custom Containers" syntax

### ISSUE THREAD

**Issue by gylidian** [valentine195/obsidian-admonition#10]
Thks for your plugin which brings admonition block-styled content to Obsidian! (●'◡'●)

But why not use "Custom Containers" syntax instead of `code-block with ad-*`
I guess it's because Obsidian doesn't provide an API related to markdown custom syntax

These are some discussion about markdown extension syntax for custom containers:
- <https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers>
- <https://github.com/markdown-it/markdown-it-container>
- <https://talk.commonmark.org/t/custom-container-for-block-and-inline/2051>
- <https://talk.commonmark.org/t/generic-directives-plugins-syntax/444>

**Comment by gylidian** [comment]
In my opinion, even if the grammar is extended grammar, it has become nominally "conventional grammar" due to the large amount of use, which is beneficial to the use experience and the difficulty of transfer

**Comment by valentine195** [comment]
> But why not use "Custom Containers" syntax instead of `code-block with ad-*`
> 
> I guess it's because Obsidian doesn't provide an API related to markdown custom syntax
 
That is correct. It would be very tedious to implement this without API support.
