### ISSUE TITLE
FontAwesome icons not working.

### ISSUE THREAD

**Issue by Infinituum17** [valentine195/obsidian-admonition#100]
I tried using a FontAwesome icon like "windows" but it doesn't work and keeps showing the example icon.

**Comment by valentine195** [comment]
Can you show me an example? They all work for me.

**Comment by valentine195** [comment]
Ah, I see. At the moment, only the "solid" icons are available.

**Comment by valentine195** [comment]
6.3.3 now includes the free regular and brand icons.
