### ISSUE TITLE
Trying to understand why Markdown standard for admonitions is not being followed

### ISSUE THREAD

**Issue by justasojourner** [valentine195/obsidian-admonition#101]
Hi Jeremy — @valentine195

Firstly thank you and kudos for making the Obsidian Admonition plug-in. I installed it and had a look around.

I read in your notes for [release 2.0.0](https://github.com/valentine195/obsidian-admonition/releases/tag/2.0.0) that you stated:

> Admonitions must be prefixed by "ad-" now to prevent collisions with other plugins.

also, not stated in the version 2.0.0 release notes, but I have seen, admonitions have to be blocked as follows:

```
    ``` ad-note
    Admonition message
    ```
```

instead of

```
!!! note
    Admonition message
```

Obviously the admonitions '[standard](https://python-markdown.github.io/extensions/admonition/)', inasmuch as Markdown has a 'standard' for admonitions, is the latter form. Material for MkDocs [also states](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) it follows that standard.

Unfortunately with respect to 'standards' in Markdown the following quote is all too true 😉 

> The nice thing about standards is that you have so many to choose from.

<cite>Computer Networks, 2nd ed.</cite>
— Andrew S. Tanenbaum

Anyway, gripes about Markdown aside, I was wondering why it is necessary for the Obsidian Admonition plug-in (Obsidian?) to change the syntax for admonitions:

1. The block code from `!!!` to ` ``` `
2. Using 'ad-type' e.g. `ad-note` instead of `note`.

I've looked at the TypeScript code but am not conversant in TypeScript and/or Obsidian plug-in code to follow fully. 

* Can you help explain the rationale/reason. Does the Obsidian core code not understand, is not able to deal with, `!!!`
* Is it possible/impossible to use the standard format. You say it clashes with other plug-ins, does that include every single Obsidian plug-in? For example if your plug-in was forked and changed to use `!!! type` (that is assuming Obsidian itself can support) what plug-ins would be affected = **_All_** community plug-ins? / **_Some_** community plug-ins? / the Obsidian written plug-ins?

**_The reason I ask_** is because I am wanting to use your plug-in for a MkDocs generated documentation website. I can (have) themed Obsidian to look almost exactly like the production website, but Obsidian lacks direct support for Admonitions. If we write admonitions the way your plug-in wants obviously they will look fine in Obsidian — but will not render on the production website — as MkDocs and Material for MkDocs are following the standard. Which sort of defeats the purpose of the exercise.

Thanks in advance for any help/guidance for this.

**Comment by valentine195** [comment]
Hi, thanks. 

The ```` ``` ```` syntax is Obsidian, yes. They allow plugins to register "languages" to code blocks, and those code blocks are then provided to the plugin to process when they are encountered by the markdown renderer. 

I switched to using the prefix for the language at the request of Obsidian's developers, because originally I was registering quite a few languages for code blocks that someone else could conceivably want to register (such as note).

**Comment by justasojourner** [comment]
Hi, thanks for getting back.

That's a shame, I suspected that it was down to how the Obsidian (internal) code does rendering. Obviously they have a parser which they have not extended to including code elements like `!!!`. 

A better way of doing it (easy for me to speak as I have not done the code but anyway) would be for them to register 'hooks' that could be handed over to an add-on or their code. So for example `!!!` could be a hook which would then call a method to deal with the related markdown. Just using ` ``` ` as a blanket hook causes issues (like you found) and makes them non-standards compliant. I mean for me (the documentation website I'm involved in) it is a dead-end. We live with not seeing admonitions live or look for another Markdown editor - which I already see are in somewhat of the same situation as Obsidian.

Markdown standards strike again!

😄 

I don't suppose there is any way of doing it (the selection part -> render) in straight CSS?

**Comment by valentine195** [comment]
> I don't suppose there is any way of doing it (the selection part -> render) in straight CSS?

There is a CSS-only solutions out there but I believe it requires it to be the *only* admonition on the page. There is another that requires the use of the Contextual Typography plugin.

How are you generating your website? Is it on Publish or some other source? I have a branch of Admonitions that has a button to generate a `js` file that looks for code blocks with the admonition types set up and tried to run the parser. At the moment I haven’t actually tested it and it doesn’t render markdown in the content, but it could be useful to you maybe?

**Comment by justasojourner** [comment]
It's using totally standard `mkdocs build` to build static HTML. The current toolset and workflow absolutely cannot be changed. Material for MkDocs is used as the theme so, again, we have to go with absolutely standard Markdown source files.

The requirement/setup I am looking at with Obsidian is to have the preview look as close as 100% possible as the production site. So when people are editing they don't need to use the MkDocs serve local web server to see produced content. Using that is a bit of a painful experience **as it rebuilds the _whole_ site on every single file change**. Which, with Obsidian, is very often. Plus setting up a whole MkDocs installation just for editors to edit documents is overkill, they won't do it.

So the idea was/is to have the Obsidian preview look exactly like the built website.

**Comment by valentine195** [comment]
Ah, gotcha. I have another plugin, Markdown Attributes, that could possibly help if you use the [Attribute Lists](https://python-markdown.github.io/extensions/attr_list/) MkDocs extension. This could let you selectively apply CSS to block quotes.

**Comment by justasojourner** [comment]
OK thanks I will review both. I'll close the issue now so it doesn't clutter up your issues list.

Thanks again for your time.

**Comment by huyz** [comment]
I also hope that the markdown "standard" were followed for interop with other Markdown tools+plugins.  Is there a feature request filed against Obsedian core to allow for parsing `!!!` ?
