### ISSUE TITLE
"See also" title for "seealso" admonition

### ISSUE THREAD

**Issue by klieret** [valentine195/obsidian-admonition#107]
Thank you for this awesome plugin @valentine195 !  Really made my day when I first found it :cat: 

Most of my admonitions are of the `seealso` type/function. That being the case, I'm a bit unhappy that the title literally is `seealso` rather than `See also`. I can of course set it explicitly with the `title:` switch, but this is cumbersome to type every time.

Would you be open to implement some special behavior that makes the title of `seealso` admonitions default to `See also`?

I could also offer to work on this if you point me in the right direction.

**Comment by valentine195** [comment]
Hi, this can be set in settings. Please create a custom seealso type and give it the same icon and color, but give it a title.
