### ISSUE TITLE
Links in admonitions aren't recognized by Obsidian

### ISSUE THREAD

**Issue by klieret** [valentine195/obsidian-admonition#108]
If I create a link

    ```ad-note
    See also [[note_name_1232342345]]
    ```

in a note `a`, then Obsidian doesn't recognize this as a link to `note_name_1232342345`. For example, `a` is only listed in the "unlinked mentions" section of the backlinks panel of `note_name_1232342345`, not in the "linked mentions" section.

This is despite having "Sync Links to Metadata Cache" turned on in `obsidian-admonition`'s settings.

**Comment by tholzschuh** [comment]
Same problem for me!

**Comment by mayurankv** [comment]
Same!

**Comment by TheAvocadoProtocol** [comment]
Same Here, 

plus there are some links that don't appear on the global graph, I've to open that note to the links to appear on the graph

**Comment by frankjonen** [comment]
Same here,

wasn't sure whether it's an Obsidian bug or a Plug-In issue.

**Comment by valentine195** [comment]
Grouped into master issue.

**Comment by copeugne** [comment]
I have a similar problem but for media attachments and didn't see it in issues already.

\```ad-info
![[duck.jpg]]
\```

It renders like I would have guessed but appears as orphan in the graph view.

<img width="1038" alt="ghissue1" src="https://user-images.githubusercontent.com/57577919/152881256-df6e28ff-ee75-4dbe-8a15-d0878f5ce155.png">

<img width="730" alt="ghissue2" src="https://user-images.githubusercontent.com/57577919/152882004-51251cda-c477-47f6-9784-9f04e0c3d3f2.png">

I'm on obsidian 0.13.23 for mac.

**Comment by KambizMoradi** [comment]
I have same problem.

**Comment by bartholome-simpson** [comment]
Hello,

I have the same problem on :
- Obsidian : 0.15.9
- Adonition 9.0.5

As soon as I create a link like below:
````
```ad-info
test: [[page]]
```
````

 The link is clickable **but** does not appear in the graph. Do you have a solution? 

Thanks a lot.
