### ISSUE TITLE
Question: is there a way to create admonitions from js, e.g. from a dataview codeblock or view?

### ISSUE THREAD

**Issue by vitaly** [valentine195/obsidian-admonition#109]

**Comment by vitaly** [comment]
hmm. I get
```
There was an error rendering the admonition:

markdown content
```

**Comment by vitaly** [comment]
![Screenshot 2021-10-21 at 16 38 04](https://user-images.githubusercontent.com/4193/138300511-275d1d74-f115-493f-b2e6-9156a6b2867d.png)

**Comment by vitaly** [comment]
Also, is there a way to render and get the inside element, so that I can then use dataview to build things inside?

**Comment by vitaly** [comment]
o!. updated and now it works! thanks!

**Comment by vitaly** [comment]
no. I need the other way around. I need to continue to build things INSIDE admonition

**Comment by valentine195** [comment]
Ah. No, that is not possible. The admonition has to have the entire markdown content you want to render when it renders.

You could just continuously append data to a string, then render it.

**Comment by valentine195** [comment]
Admonition content is deeply nested. You can find it using `admonitionEl.querySelector('.admonition-content')`.

**Comment by vitaly** [comment]
since the last time?

**Comment by vitaly** [comment]
how do I control the rest of admonition params? e.g. title, icon, etc?
