### ISSUE TITLE
PDF Rendering Issues in some PDF Viewers

### ISSUE THREAD

**Issue by dpurnomo** [valentine195/obsidian-admonition#11]
See image. From what I tested, the ones that looks good is `tip`, `success`, `example`, and `bug`.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/19817105/115946039-ce926280-a4e8-11eb-833d-aad9ab1e9a9c.png">

**Comment by valentine195** [comment]
I just tested this with both the light and dark theme and it looks fine to me:

[Dark](https://github.com/valentine195/obsidian-admonition/files/6385976/Admonition.All.pdf)
[Light](https://github.com/valentine195/obsidian-admonition/files/6385977/Admonition.All.light.pdf)

Can you confirm if this happens in other PDF viewers?

The only possibility I can think of that would be causing that grey box would be the box shadow, but that is applied to all of the admonitions. You could try this also, in your custom CSS:

```css
.admonition {
     box-shadow: unset;
}
```

**Comment by dpurnomo** [comment]
I tried the custom CSS and result still the same.

For what it is worth, it seems this affects only the default PDF renderer in MacOS/iOS. If I open the PDF in Google Chrome or Brave, everything looks fine. But in Preview or Safari, it is still the same. It is also the same issue if the PDF is opened on my iPhone.

MacOS Preview
<img width="664" alt="image" src="https://user-images.githubusercontent.com/19817105/116684594-54c41280-a9db-11eb-8553-e9062067d490.png">

iPhone
![image](https://user-images.githubusercontent.com/19817105/116684633-60173e00-a9db-11eb-9e9a-af979001e228.png)

**Comment by valentine195** [comment]
Honestly, this has me stumped. I have no idea why they would render differently - the separate admonitions do not receive any specific styling by default. All of the CSS is the same on every admonition except for the color variable.
