### ISSUE TITLE
regression: nested dataview codeblocks no longer work:

### ISSUE THREAD

**Issue by vitaly** [valentine195/obsidian-admonition#110]
this used to work:
~~~markdown
```ad-note
title: TITLE
collapse: open
```dataview
LIST
```
~~~
but now produces an empty admonition

**Comment by WychWitch** [comment]
Yep, having the same issue! I thought it was just me. Here's a photo if that's needed!

![image](https://user-images.githubusercontent.com/1291820/138378126-54155a91-9fbc-415a-ac05-90c8a740a986.png)

![image](https://user-images.githubusercontent.com/1291820/138378139-3c0b48ac-0e61-434f-845d-e98408b40323.png)

**Comment by valentine195** [comment]
Is this still an issue?

**Comment by nfelnlp** [comment]
> Is this still an issue?

Not anymore, works with the current version! You can close it. Thanks!
