### ISSUE TITLE
admonition embeds don't work from inside dataview view.js

### ISSUE THREAD

**Issue by vitaly** [valentine195/obsidian-admonition#112]
not sure if problem with dataview or admonition.
the following code works when running from dataview codeblock, but when running from dataview js, it doesn't create an embed, just prints 'test.png' instead:
~~~javascript
dv.app.plugins.plugins["obsidian-admonition"].postprocessor(
  "note",
  "![[test.png]]",
  dv.container.createDiv()
);
~~~

**Comment by valentine195** [comment]
This is because Dataview runs their post processor asynchronously, I believe. Embeds must be synchronous.
