### ISSUE TITLE
Content being moved out of non-codeblock admonition

### ISSUE THREAD

**Issue by MathewBlanc** [valentine195/obsidian-admonition#113]
Hi! 

Just wanted to let you know about an issue I've been having with the non-codeblock admonition feature. 

**Markdown view**

![image](https://user-images.githubusercontent.com/24759337/138374042-62b2270f-8751-4d34-9131-07c8a0ccf564.png)

(note: "ex" is a custom admonition I've created)

**Preview**

![image](https://user-images.githubusercontent.com/24759337/138374086-c81f58c4-11e2-46a1-ac8f-4505df7b8d92.png)

**Issue**

Basically, the content from within the admonition is being rendered outside the admonition in preview mode. It also appears to be a bit unstable, in that it was originally showing the table within the admonition, but the 'Correspondences' bold text and content was outside. I restarted obsidian to see if that would fix the issue, and now it's rendering _all_ the content outside.

**Set up**

This is on an M1 mac, with the latest version of obsidian (0.12.19)

**Comment by valentine195** [comment]
I would recommend using the new [MS Doc](https://github.com/valentine195/obsidian-admonition#microsoft-document-syntax) syntax instead of the `!!!` syntax. I am going to be phasing the old syntax out over the next few versions, and it is buggy, unstable, and unlikely to ever improve.
