### ISSUE TITLE
It will report an error if used in conjunction with the admonition plug-in

### ISSUE THREAD

**Issue by tyf2018** [valentine195/obsidian-admonition#116]
I want to filter out unlabeled files. Currently, I use this way of writing:

> where !file.tags

This way of writing works normally, but it will report an error if used in conjunction with the admonition plug-in.

![image](https://user-images.githubusercontent.com/56342788/139375260-e269d7b8-281e-4bbe-99e8-82fc1ded1a61.png)

Can anyone give me advice or share a solution? Thanks!

I have feedback this question in the discussion area of Dataview, and the author has also answered it, please refer to the details: 

[Screening method for unlabeled files · Discussion #593 · blacksmithgu/obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview/discussions/593)

**Comment by valentine195** [comment]
This works for me as of Obsidian 0.13.3
