### ISSUE TITLE
Footnotes not displaying properly

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-admonition#117]
![image](https://user-images.githubusercontent.com/29135984/139688290-2771ab4c-33dd-4f55-904f-ebd168454148.png)
The mouse pointer is placed on this line before it is displayed in full
![image](https://user-images.githubusercontent.com/29135984/139687925-dca7abc0-09d5-4fe7-a4df-6febdbbbee87.png)

![image](https://user-images.githubusercontent.com/29135984/139688042-a4e8166f-491c-424e-aae8-2b93bf22016a.png)
![image](https://user-images.githubusercontent.com/29135984/139688800-a6927f2f-df7d-46ba-a22c-27e62b9f797a.png)

**Comment by valentine195** [comment]
This is because Obsidian's plugin API markdown renderer does not parse these, unfortunately. If you absolutely need these in an admonition, you should use the "Non-Code block Syntax"
