### ISSUE TITLE
Adding a table in code block style admonition

### ISSUE THREAD

**Issue by ZayrX** [valentine195/obsidian-admonition#119]
It seems like tables are not rendered in the admonition or do I need to escape tables somehow? I tried to add more backticks but that also doesn't work and I couldn't find anything in the documentation.

![image](https://user-images.githubusercontent.com/7146961/140335440-7cce29fd-c477-47a7-880f-ba8f2c576997.png)

Is rendered as

![image](https://user-images.githubusercontent.com/7146961/140335481-66d4f599-8099-4d0c-8d79-5b24d732eebe.png)

adding more backticks
![image](https://user-images.githubusercontent.com/7146961/140336313-02e730f3-f512-4806-ae5b-3da263ecd25d.png)

Is rendered as

![image](https://user-images.githubusercontent.com/7146961/140336356-3962df01-4162-470f-805d-274cb3594808.png)

**Comment by valentine195** [comment]
I believe you need a space between "Overall Impact:" and the table. This behavior is also present in normal Obsidian markdown.
