### ISSUE TITLE
Syntax-Highlightin inside the block

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#12]
It would be nice to get the same colors inside the ad-note or whatsoever, that are also displayed in plain markdown.

**Comment by valentine195** [comment]
Could you give me an example of what you would like to see?

**Comment by TobiasKlosek** [comment]
sure, here you go:

![image](https://user-images.githubusercontent.com/61796661/116275102-93f82680-a783-11eb-9a1d-3776f0c9d45b.png)

**Comment by TobiasKlosek** [comment]
sure, here you go:

![image](https://user-images.githubusercontent.com/61796661/116275206-b25e2200-a783-11eb-94a1-21b147070a31.png)

**Comment by valentine195** [comment]
Please note that *this is a setting that is off by default.*

**Comment by TobiasKlosek** [comment]
Could you please provide more Info on that setting? 
Where to find and enable it for e.g.

**Comment by valentine195** [comment]
Yes, it is in the Settings menu of Obsidian, in the plugin settings tab.

**Comment by TobiasKlosek** [comment]
Sorry, but i dont know what you are talking about.. 

Can you provide a screenshot of that specific option i have to activate to get syntax-highlighting inside your plugin?

**Comment by valentine195** [comment]
Sure:

![Untitled](https://user-images.githubusercontent.com/38669521/116295142-c5aec480-a766-11eb-9960-78ef75ada829.png)

The buttons may look different depending on the theme you have installed.

**Comment by TobiasKlosek** [comment]
thanks, i havent updated to no setting was shown. Thanks! It works now!

**Comment by valentine195** [comment]
Great, glad you could find it. Let me know if you run into any issues with the highlighting.
