### ISSUE TITLE
File in admonition do not show backlinks

### ISSUE THREAD

**Issue by Miroier** [valentine195/obsidian-admonition#120]
For example, i create a admonition in [[Windows Software]] like this:

````
```ad-summary
title: pdfReader
collapse: open

1. [[SumatraPDF]]

```
````

when i click into the [[SumatraPDF]] page, i cant find the [[Windows Software]] in Linked mentions.

additionally, if i rename the [[SumatraPDF]], it won't react to the [[SumatraPDF]] in [[Windows Software]].

I think it's the same problem

**Comment by valentine195** [comment]
This is because Obsidian does not parse code blocks for links. You can use the setting "Sync Links to Metadata Cache" to try to help with this, but it is _not_ officially supported behavior for Obsidian and may not work 100% correctly.
