### ISSUE TITLE
Collapsible Extra Arrow

### ISSUE THREAD

**Issue by Talistan12** [valentine195/obsidian-admonition#124]
The collapsible admonitions are not working properly, displaying an extra arrow above the title that is also toggled when the admonition is collapsed/not collapsed. Increases the height of the admonition unnecessarily. Tried swapping to a different theme and that did not fix the issue.

![image](https://user-images.githubusercontent.com/17948170/141969396-c607dc9a-ca7d-4e48-88e9-417b75de3dd2.png)

![image](https://user-images.githubusercontent.com/17948170/141969423-d3f3a9a4-d3fc-44bc-819d-cbb16074eb57.png)

**Comment by valentine195** [comment]
Hi, this usually happens because of an old installer version. Can you please install the latest installer from the Obsidian website and then try again?

**Comment by Talistan12** [comment]
cool, that fixed it, thank you!
