### ISSUE TITLE
ad-tldr does not appear to work

### ISSUE THREAD

**Issue by CKHarwood** [valentine195/obsidian-admonition#125]
The `ad-tldr` admonition block does not display as an admonition. Other admonition blocks that I have used still work. The screenshot below shows `ad-tldr` not working alongside `ad-summary` working.

![image](https://user-images.githubusercontent.com/1888159/142071117-7ae043e1-e55d-45a8-bccd-52dac61907c1.png)

**Comment by valentine195** [comment]
Not sure how that got taken out of there! Just pushed a release to add it back in.
