### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by charleshan** [valentine195/obsidian-admonition#126]
This is probably related to Code blocks and how Obsidian creates the index but this means that the Search, Page links, and Tags don't work inside admonition.

> this is an unfortunate side effect of the plugin being a code block processor. Links and tags are not added to Obsidian’s cache, so Obsidian won’t update or track them.
https://forum.obsidian.md/t/admonition-plugin/176/63

**Comment by valentine195** [comment]
> This is probably related to Code blocks and how Obsidian creates the index

Correct. It is unlikely that I'll be able to improve this behavior until Obsidian creates an alternative code block syntax that it will process (similar to how they added an alternative comment syntax).
