### ISSUE TITLE
Live Preview Render of Non-Codeblock Admonitions

### ISSUE THREAD

**Issue by tim-hilde** [valentine195/obsidian-admonition#128]
As code blocks are now rendered in Live Preview, I wonder wether it'll be possible to render non-codeblocks in LP as well?

**Comment by valentine195** [comment]
The post processor that non-code block admonitions use is not supported in LP yet. 

They will also probably need further updates to work for LP, as right now they are a bit hacky in how they work in preview mode.

**Comment by tim-hilde** [comment]
Okay, good to know. So it's just a matter of time then

**Comment by valentine195** [comment]
This is unlikely to be supported as I would need to write a CodeMirror 6 extension for this. Closing.
