### ISSUE TITLE
Option to rename built-in admonistion name types and rtl support

### ISSUE THREAD

**Issue by Alexnoj** [valentine195/obsidian-admonition#129]
Can you add option to rename the built in admonistion name types? - I want to translate them to my language.

In addition, can you add support to RTL language of style?
I solve it by change these lines:
```
.admonition
 border-right: 0.2rem solid rgb(var(--admonition-color));
    border-left: 0; 

```

```
details.admonition > summary > .collapser
left: 8px;
```

**Comment by valentine195** [comment]
> Can you add option to rename the built in admonistion name types? - I want to translate them to my language.

I'm sorry, but I'm not sure of a good way to do this that doesn't involve the user creating custom admonitions, so I would suggest creating custom ones and not using the defaults.

> In addition, can you add support to RTL language of style?

I can add this in the next release, but it seems like you've already solved it :)
