### ISSUE TITLE
Suggestion: Use Microsoft Document Syntax

### ISSUE THREAD

**Issue by Andy-AO** [valentine195/obsidian-admonition#133]
Using code blocks is prone to incompatibilities.

It's a good idea to use a scheme that has been widely verified.

Note that Microsoft's markdown document syntax is very good. It is not only completely legal, has good compatibility, but also easy to read.

example

```MarkDown
> [!NOTE]
> This parameter is not supported by any providers installed with PowerShell.
> To impersonate another user, or elevate your credentials when running this cmdlet,
> use [Invoke-Command](../Microsoft.PowerShell.Core/Invoke-Command.md).
```
![](https://cdn.jsdelivr.net/gh/Andy-AO/GitHubPictureBed/img/20211205074858.png)

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.2

**Comment by valentine195** [comment]
How do you end the comment, or is it just the next line? Also, is your link correct?

Adding markdown syntax to Obsidian through their API is actually pretty difficult, unfortunately.

**Comment by valentine195** [comment]
This was added in 6.8.0. See [here](https://github.com/valentine195/obsidian-admonition#microsoft-document-syntax) for syntax.
