### ISSUE TITLE
Tasks in admonition block unclickable

### ISSUE THREAD

**Issue by Rainbell129** [valentine195/obsidian-admonition#135]
Admonition version 6.7.2

Hi, I have been using admonition for quite some time now and it really amazes me that most of the dynamic functions work fine with the plug-in unlike with other kinds of code blocks.

However when I tried to put some tasks in admonition blocks I found them to be unclickable.

```ad-note
- [ ]  ddd
- [ ] ssss

````

Is this an issue that can be fixed? It would be extremely helpful if I can add tasks in admonition blocks.

**Comment by uwe999** [comment]
I second that. You can change the task in edit mode but can't click them in preview mode

**Comment by valentine195** [comment]
Hi, this should be fixed in 6.7.3. Sorry this took so long!

**Comment by Rainbell129** [comment]
Lovely! Thank you so much!
