### ISSUE TITLE
"Extra" collapsible arrow icon?

### ISSUE THREAD

**Issue by felipemldias** [valentine195/obsidian-admonition#136]
Hi there! For some reason whenever I use the collapse parameter an extra arrow will show up, just like the one in collapsible headings:

![Screenshot at Dec 16 22-53-22](https://user-images.githubusercontent.com/63819261/146475944-b6e26f0e-0232-4114-bc6f-a686bb9a1c39.png)
![Screenshot at Dec 16 22-53-47](https://user-images.githubusercontent.com/63819261/146475949-5bd8e396-4674-42e9-ad9a-5dc8f429966a.png)

I believe this isn't the expected behaviour, as per the illustration on the plug-in page: 

![image](https://user-images.githubusercontent.com/63819261/146476173-489462cd-9171-4cde-b3bf-165d38bef575.png)

I've tried the normal theme and also different ones, but the issue persists. My codeblock has nothing exceptional typed in it, so I'm not sure what could be causing this.

**Comment by valentine195** [comment]
This is typically caused by having an old installer version. Can you try redownloading Obsidian and reinstalling it?

**Comment by felipemldias** [comment]
That did it! Thank you (:

**Comment by valentine195** [comment]
Great news!
