### ISSUE TITLE
use color names instead of rgb values

### ISSUE THREAD

**Issue by uwe999** [valentine195/obsidian-admonition#137]
it would be nice to be able to just specify a color name instead having to lookup rgb values.
For example https://www.w3schools.com/colors/colors_names.asp

**Comment by valentine195** [comment]
In what? CSS? Settings when creating the Admonition?

**Comment by uwe999** [comment]
ideally on both.
For example, by adding a "color by name" selection box to the color picker
<img width="266" alt="image" src="https://user-images.githubusercontent.com/19934504/148435904-82c8af51-e54a-4623-99c4-b707010651e3.png">

Then in the code allow overriding the color by name
`
```ad-<type> # Admonition type. See below for a list of available types.
title:                  # Admonition title.
collapse:               # Create a collapsible admonition.
icon:                   # Override the icon.
color:                  # Override the color.
colorname:          #override the color by name
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla.
```
`

I use admonitions a lot now, have replaced all my standard block quotes (>) with custom ad-quotation type triggered by CTRL+q and I can search for all my quotes in search or list with with the query feature or dataview.
Love it! Thanks!

**Comment by valentine195** [comment]
That is the Chrome color picker, I can’t change it :) I may be able to override it. I’ll think about this.

**Comment by uwe999** [comment]
oic. Don't sweat it, it's not that important

**Comment by ngirard** [comment]
Greetings,

It would be great if colors already defined as CSS variables from themes/snippets would be recognized.

I'd suggest the syntax to be identical to css:
```
color: var(--my-defined-color)
```

Cheers !

**Comment by valentine195** [comment]
You can turn off `Set CSS Colors` in settings and admonitions will receive no color information from the plugin. You can then define the colors yourself in CSS. The [Ebullientworks theme](https://github.com/ebullient/obsidian-theme-ebullientworks) does this.
