### ISSUE TITLE
Images in live preview don't work

### ISSUE THREAD

**Issue by ndharari** [valentine195/obsidian-admonition#138]
Images inside admonitions don't work in live preview either in read or edit mode

mwe:
```
ad-note
![[img.png]]
```

The image is not rendered. When scaling, only renders the scale factor ie, ![[img.png|300]] --> 300.
When editing inside the admonition codeblock, it renders correctly.

**Comment by cbourget** [comment]
I got the same issue since the latest Obsidian release.

**Comment by valentine195** [comment]
Hi, unfortunately in 0.13+ Obsidian made it not possible for me to render embeds inside admonitions. I asked the dev if he had any possible workarounds in mind but haven’t heard back yet.

**Comment by cbourget** [comment]
Thanks Jeremy for your quick response. I'll fallback to version 0.12 for now.

**Comment by daniellsh** [comment]
I have the same issue too. How can I make a version fallback in obsidian?

**Comment by cbourget** [comment]
I'm sure there is a better way but here's what I ended up doing after a few failed attempts at stopping Obsidian from auto updating itself.

On linux, when running the AppImage of version 0.12.19, Obsidian will look for this file `~/.config/obsidian/obsidian-0.13.14.asar`. If it can't find it, then I'll fetch it from github and proceed to update.

What I did is I created a file with that name, fooling Obsidian into thinking it had been upgraded to 0.13.14 while still running 0.12.19.

**Comment by valentine195** [comment]
Hey all, those of you with insider access - this issue should be fixed on Obsidian's side in the latest insider release.

**Comment by Archie-2021** [comment]
i am having the same issue. hope this get resolved soon

**Comment by valentine195** [comment]
Closing this because it is fixed on Obsidian's side in the Insider release.
