### ISSUE TITLE
[Request] - Align Text/Chapter to corresponding Icon

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#14]
As you can see, there is some misalignmet between the Icon and the Text. Would be nice to have that centered.
![image](https://user-images.githubusercontent.com/61796661/116401491-98781a00-a82b-11eb-928c-28b4e79dcc8d.png)

**Comment by TobiasKlosek** [comment]
Taken from here: https://squidfunk.github.io/mkdocs-material/reference/admonitions/

![image](https://user-images.githubusercontent.com/61796661/116401964-218f5100-a82c-11eb-98ae-1ecd92f55e80.png)

everything seems to be centered.

**Comment by valentine195** [comment]
Should be properly centered in 3.2.1.

Are you doing additional styling to the icon? It looks much smaller than I would expect.

**Comment by TobiasKlosek** [comment]
Thanks! No, didnt change anything..

**Comment by valentine195** [comment]
Interesting. Is the title being rendered as a header, perhaps?

I think seeing the screenshot raised another issue with rendering the title as Markdown - I should try to match the icon size to the font size of the title.

**Comment by TobiasKlosek** [comment]
Yes, the title is rendered as a header! (Very nice btw!!)

Resizing the Icon accordingly to the Font size would be awesome!

**Comment by valentine195** [comment]
As of 3.3.0, icon size will respect font size of title element.
