### ISSUE TITLE
Nested codeblocks don't appear correctly in Live Preview

### ISSUE THREAD

**Issue by mayurankv** [valentine195/obsidian-admonition#142]
Nested codeblocks don't appear correctly in Live Preview. Only the inner codeblock is renedered (whether using ~~~ or ``` for the inner codeblock). Ideally all codeblocks would be rendered.  This is shown in the below image. I haven't experimented with non codeblock admonition boxes but I'm under the impression those don't work in live preview either?

![image](https://user-images.githubusercontent.com/69591376/147353634-b25e6011-5caa-41e2-a884-b2945f6447af.png)

**Comment by GOUKOU007** [comment]
It rendered correctly on my mechine.
Did you use any other plug-ins that might cause conflict.

![](https://s2.loli.net/2021/12/29/cwdu6lPigYqHUQk.png)

**Comment by dariuszkowalski-com** [comment]
I have got the some problem:
![image](https://user-images.githubusercontent.com/37656900/149333211-6649cc4c-c795-4f3e-96e9-3da5fd3a8078.png)

render in Live Preview Mode:
![image](https://user-images.githubusercontent.com/37656900/149333256-983739a2-d951-4112-b6ce-fda1e8d4b5e0.png)

but in Preview mode:
![image](https://user-images.githubusercontent.com/37656900/149333412-aaa37d5f-860a-4332-bf32-3e74aa4a90b0.png)
it looks ok

**Comment by mayurankv** [comment]
Well its working now! Not sure what changed but thank you! I'll close this issue.

**Comment by dariuszkowalski-com** [comment]
no, it doesn't work

**Comment by dariuszkowalski-com** [comment]
@mayurankv  please reopen in

**Comment by valentine195** [comment]
> no, it doesn't work

Are you talking about queries, or nested Admonitions?

**Comment by valentine195** [comment]
The query embed is a different issue. See #155.

**Comment by dariuszkowalski-com** [comment]
> > no, it doesn't work
> 
> Are you talking about queries, or nested Admonitions?

embeded queries

**Comment by valentine195** [comment]
See #155
