### ISSUE TITLE
[BUG] Mentioning header inside admonition codeblock

### ISSUE THREAD

**Issue by Pheggas** [valentine195/obsidian-admonition#143]
Hello. I got an issue with Admonition.

I typed some text inside the admonition todo codeblock and wanted to mention header inside the same note. So i did `[[#Docker container startup | Test` so it should create clickable link to the header "Docker container startup" and name it "Test". Well, it did it properly but it also created new connection to non-existing note called "#Docker container startup" which, obviously, is the name of the header i mentioned in that note.

Visually it looks like this:
![image](https://user-images.githubusercontent.com/9994511/147821516-aa725106-1ffe-4a73-9aad-24afe08f34c6.png)

Where the green bubble is the note in which i mentioned that header and #Docker container startup is name of the header.

In edit mode it looks like this:
![image](https://user-images.githubusercontent.com/9994511/147821675-0bcac1d2-677f-438c-b6fd-a21aaa66c66e.png)

(I used different name for the mentioned header but it doesn't matter)

Let me say one more thing. I tried this same thing without the codeblock and it worked as expected (Create clickable link and scroll to the header but not creating and linking non-existing note with the same name as the header)

PS: Could someone replicate this so i can be 100% sure it is bug within Admonition?

Steps to replicate:
1. Create note
2. Add header 
3. Add admonition codeblock
4. Mention that header inside the codeblock
5. Click on that mention in view mode
6. Go to graph view and see connection between your note and the non-existing note with the name of header.

Obsidian version: 0.13.14
OS: Windows 10

**Comment by valentine195** [comment]
> Well, it did it properly but it also created new connection to non-existing note called "#Docker container startup" which, obviously, is the name of the header i mentioned in that note.

Is this bug just that it created the link wrong in graph view? The link worked properly in the Admonition?

**Comment by Pheggas** [comment]
> > Well, it did it properly but it also created new connection to non-existing note called "#Docker container startup" which, obviously, is the name of the header i mentioned in that note.
> 
> Is this bug just that it created the link wrong in graph view? The link worked properly in the Admonition?

Yes, the link works perfectly and only appears when using Admotion custom codeblocks.

**Comment by valentine195** [comment]
Okay, merging this with #144.
