### ISSUE TITLE
Links, Tags, and Footnotes Inside Admonitions

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-admonition#144]
This issue is to collect all issues related to links, tags, and footnotes, and their behaviors, inside Admonitions.

Relevant issues: #36, #97, #103, #108, #132

Admonitions can try to add links it finds in its content to the Obsidian Metadata cache, but there is currently no way to permanently add these items.

There is an [open issue](https://github.com/obsidianmd/obsidian-api/issues/33) on the Obsidian API repository related to plugins being able to natively add links to the metadata cache. The behavior of Admonition's link handling will not be improved unless this issue is closed.

**Comment by valentine195** [comment]
This is getting tagged as wontfix because Obsidian has added callouts as a core feature to the latest insider build. If you need links or footnotes to work without callouts, you should use that syntax.

**Comment by mayurankv** [comment]
For relevance to any other devs, I was also having a similar issue so I created a forum post about this issue [here](https://forum.obsidian.md/t/api-method-to-add-link-and-have-it-parsed-into-metadatacache/72046). Please go and comment/like this if you want this to be resolved!
