### ISSUE TITLE
Custom Prefixes

### ISSUE THREAD

**Issue by ndharari** [valentine195/obsidian-admonition#145]
Could we add custom prefixes when the "insert admonition with title" is used?
Maybe this can already be done but I'm new to all of these plugins

This could be usefull to define a "Definitions" or "Proofs" ad that could work like this: 

```ad-dfn
title: Definition: **Law of Total Variance** (Eve's Law)
$$
\operatorname{Var}(Y)=E(\operatorname{Var}(Y \mid X))+\operatorname{Var}(E(Y \mid X))
$$
```
And the "Definition: " part comes prefilled

**Comment by valentine195** [comment]
so basically you want the command to always insert this?

```
title: Definitions

```

**Comment by ndharari** [comment]
Pretty much

**Comment by ndharari** [comment]
Hi sorry to bother. Do you think this is something doable? (or that you have any interest to add? 
If not, the pluggin is the best

**Comment by ndharari** [comment]
You are really the best, thanks!
