### ISSUE TITLE
[BUG] Can't load the plugin on IdeaPad Duet (Android version)

### ISSUE THREAD

**Issue by TRENEEDANAME** [valentine195/obsidian-admonition#146]
I can't load the plugin on Chromebook IdeaPad Duet (Android version)

I tried to reinstall, do a clean Obsidian install... Nothing work.

**Comment by valentine195** [comment]
I'm sorry, I don't have access to an Android device to debug this. v6.7.5 does load on my iPhone, and generally iOS is more restrictive. If you can give me any further information I can try to fix it.

**Comment by valentine195** [comment]
Someone on the Obsidian discord just said they could install and enable the plugin on their Android 9 device.

**Comment by TRENEEDANAME** [comment]
Hello, I tried again after updating everything, it still does not load (on my smartphone (Android) it does load), I only have problem with my Chromebook (The Linux version of the app doesn't work either for this machine as on my PC it work fine (Arch Linux)

If I can give more detail, I will do

**Comment by valentine195** [comment]
Do you know what version of Android it is running?

**Comment by TRENEEDANAME** [comment]
I think it's Android 9

**Comment by TRENEEDANAME** [comment]
> Do you know what version of Android it is running?

I think it's Android 9

**Comment by valentine195** [comment]
Is this still an issue? I haven’t found anyone be able to reproduce this.

**Comment by TRENEEDANAME** [comment]
This is now fixed. It seems to come and go as update are applied. For now it's fixed
