### ISSUE TITLE
[BUG] Stuck when rendering MS Document Syntax in Live Preview

### ISSUE THREAD

**Issue by shodankim** [valentine195/obsidian-admonition#149]
If rendering MS Document Syntax is enabled, when scrolling through a page which has some admonitions used, the page is cut off and Obsidian is stuck; unable to click or type anything in Obsidian. This does not happen if the rendering option is disabled

After scrolling through the page:
![image](https://user-images.githubusercontent.com/66750905/149012065-20187a1a-8cad-4222-9657-414a833b0203.png)

Original page:
![image](https://user-images.githubusercontent.com/66750905/149012494-fc8ee603-8e41-4c58-84f1-afad04be7ca8.png)

**Comment by valentine195** [comment]
Can you open the developer console and let me know if there are any errors when this happens?

ctrl+shift+i (windows/linux) cmd/opt/i (mac)

**Comment by shodankim** [comment]
The developer console can't seem to pick anything out of the ordinary...
![image](https://user-images.githubusercontent.com/66750905/149014174-a295dc21-8c3c-4bb1-8aed-795645cfc981.png)

Trying to close the console works, but reopening the console after the bug takes place doesn't work:
![image](https://user-images.githubusercontent.com/66750905/149014391-c9384609-aa44-4d29-a639-dcd1479c94aa.png)

**Comment by valentine195** [comment]
If you are comfortable with it, could you share a note that errors?

**Comment by valentine195** [comment]
I was able to reproduce - please try 6.9.3 and see if this still happens.
