### ISSUE TITLE
[Request] - If Box is collapsable, expand it by default

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#15]
By now, everytime an Note with an expanded Box is closed an reopened, it will display the boxes collapsed. 
Would nice to have an option to disable that, so that all boxes are expanded by default.

**Comment by valentine195** [comment]
Did you try this? 

https://github.com/valentine195/obsidian-admonition#collapsible

> collapse: open will start the admonition opened on render, but allow collapse on click.
