### ISSUE TITLE
Weird jumping with MS Syntax

### ISSUE THREAD

**Issue by tim-hilde** [valentine195/obsidian-admonition#151]
https://user-images.githubusercontent.com/44113468/149118034-044242be-df30-4a5e-801b-b6e5d57a16a5.mov

**Comment by tim-hilde** [comment]
Any feedback on this? Can't use admonitions at all due to this bug

**Comment by valentine195** [comment]
But yeah, I see that editing a note below an admonition can be a little weird. Let me see if I can improve this - LP is hard, unfortunately.

**Comment by valentine195** [comment]
Is this Admonition the **very first line** of the note?

**Comment by tim-hilde** [comment]
Yes, I'm moving the cursor up/down, but it also happens with moving left or right. Also when clicking somewhere. And yes, the Admonition is the very first line of the note

**Comment by valentine195** [comment]
> And yes, the Admonition is the very first line of the note

Yes, I thought so. I know what is happening, still hunting down why.

If you add an extra line above or two the Admonition, this behavior should stop, but I will try to find a fix.

**Comment by valentine195** [comment]
Obsidian has implemented MSDoc-syntax callouts to the latest insider build as a core feature, so this syntax has been removed from Admonitions.
