### ISSUE TITLE
Changelog displayed by "Plugin Changelog" always show "Chore"...

### ISSUE THREAD

**Issue by stecydube** [valentine195/obsidian-admonition#152]
I use the "Plugin Changelog" to see the changelog but under every version it is always, for example:
>  chore(release): 6.9.3

I guess the plugin is taking the text under the "releases" thread and not the changelog.md file.

Maybe having the text in the changelog for a particular release also be added to the description of the release? 😉

**Comment by valentine195** [comment]
This should be better now

**Comment by stecydube** [comment]
It is 😀
Much better 👍
