### ISSUE TITLE
Incorrect edit  for Microsoft Document Syntax i n Live preview mode

### ISSUE THREAD

**Issue by dariuszkowalski-com** [valentine195/obsidian-admonition#153]
When I put this:

> [!quote]
> This is an admonition!

I see a Quote addnotation - it's ok.

I can't edit it by jus simple enter a cursor on the code. 

I need to use  "Edit this block" button.

**Comment by valentine195** [comment]
This is the same way the regular code block admonitions work in LP.

If you select the admonition, it will turn into a block quote again and you can edit it.
