### ISSUE TITLE
Obscure live preview rendering issue when using Microsoft Document Syntax

### ISSUE THREAD

**Issue by DaveyUS** [valentine195/obsidian-admonition#156]
So I recognize this is probably a _very_ niche issue and it's possible that I'll be the only person that will ever experience this due to my setup. I would completely understand if you skipped this one to spend your time on more valuable issues. That said, any help is greatly appreciated.

I have a python setup that inserts things into my notes externally. After I insert something, my admonition acts very buggy (see video below). Clicking lines unassociated to the admonition will rip it out of the rendered mode into edit mode. Refreshing obsidian will fix the issue until the next time I edit the file externally, which is often.

Let me know if there's anything you want to know, and thanks for your time!

https://user-images.githubusercontent.com/53842399/150041600-92bbcf5b-9138-4e0b-84c0-06d5077ce347.mp4

**Comment by DaveyUS** [comment]
Just realized this may be a bigger bug than initially thought. This issue presents itself randomly when manually typing a tag into a note too.

**Comment by valentine195** [comment]
This is probably similar to #151. There's something weird going on with Obsidian's underlying CodeMirror 6 API and replacement widgets. I talked to people on the Discord about the other issue and maybe have a potential fix once I get a chance to try it out.

**Comment by valentine195** [comment]
Obsidian has implemented MSDoc-syntax callouts to the latest insider build as a core feature, so this syntax has been removed from Admonitions.
