### ISSUE TITLE
Inconsistent Microsoft style admonitions

### ISSUE THREAD

**Issue by dbarenholz** [valentine195/obsidian-admonition#158]
Related discord message: <https://discord.com/channels/686053708261228577/707816848615407697/934439747810623588>

Related image:
![image](https://user-images.githubusercontent.com/25849034/150640919-ccda66fc-5d27-4a27-bd6c-bf28f322b90e.png)

Description:
Your syntax for MS admonitions is not the same as what you link to in the settings!

**Comment by valentine195** [comment]
Closed in v6.9.7

I clarified in the ReadMe that the syntax is inspired by, and the type used is case sensitive and must match exactly.
