### ISSUE TITLE
Nested admonition refers to wrong title

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#16]
It seems, that the `title` references to the wrong admonition:

![image](https://user-images.githubusercontent.com/61796661/116521327-20b1fa00-a8d4-11eb-8b07-9749ff732529.png)

leads to:

![image](https://user-images.githubusercontent.com/61796661/116521347-26a7db00-a8d4-11eb-9298-833f4a114b0f.png)

**Comment by valentine195** [comment]
Nested admonitions are going to be buggy in general because of the way Obsidian handles code blocks. I'll think about this - admonitions inside other admonitions may require a different syntax, so that I can recursively pull them out of the source code.

**Comment by TobiasKlosek** [comment]
That would be awesome. I would use nested admonitions very often, so this would be really a big benefit :)

**Comment by valentine195** [comment]
Please see [Nesting Admonitions](https://github.com/valentine195/obsidian-admonition#nesting-admonitions) for documentation on how to nest admonitions.

**Comment by valentine195** [comment]
Hi, just wanted to let you know that I've updated the documentation relating to nesting admonitions. Additional markdown syntax was brought to my attention by @mitasov-ra.

Please check [Nesting Admonitions](https://github.com/valentine195/obsidian-admonition#Nesting-Admonitions) and [Rendering Code Blocks inside Admonitions](https://github.com/valentine195/obsidian-admonition#rendering-code-blocks-inside-admonitions)
