### ISSUE TITLE
how to custom block or prefix

### ISSUE THREAD

**Issue by pincman** [valentine195/obsidian-admonition#162]
like 
```
:::note

Some **content** with _markdown_ `syntax`. Check [this `api`](#).

:::
```
for docusaurus

**Comment by valentine195** [comment]
Custom admonition types can be created in settings. See [here](https://github.com/valentine195/obsidian-admonition#custom-admonitions).

**Comment by MatAmo93** [comment]
Hey @valentine195 sorry for brining this back up, but i also want to do the same. 
And i totally struggle, with the custom settings.
Basically have with `:::note` at the beginning as prefix and `:::` as suffix.
https://docusaurus.io/docs/2.0.1/markdown-features/admonitions

This can then be used directly to deploy to Docusaurus.

Could this be somehow done?

**Comment by valentine195** [comment]
No, custom syntax is extremely difficult and brittle, sorry.
