### ISSUE TITLE
Unable to collapse note in LP

### ISSUE THREAD

**Issue by richukuttan** [valentine195/obsidian-admonition#165]
Hi,

In Live Preview, whenever I move my mouse to the top-right of the note (where the hide tool is present), the "Edit this block" option from LP pops up and completely covers the underlying hide tool.

I'm not sure what can be done to change this behavior.

Thanks!

current version:

Obsidian: v0.13.23
Admonition: v6.9.8

**Comment by I-Pch** [comment]
Hi @richukuttan 😊 

I faced the same problem but I also discovered that you don't need to actually click on the "collapse arrow" at the top right corner of the admonition ... you can click anywhere in the "title banner" of the admonition to collapse it 😊 ...
