### ISSUE TITLE
Checkboxes are not getting updated in Live Preview

### ISSUE THREAD

**Issue by VeroVerro** [valentine195/obsidian-admonition#166]
Hi! I looked at the existing issues and I'm not sure if this is related to this: https://github.com/valentine195/obsidian-admonition/issues/9

The problem is that ticking a checkbox doesn't update the source / doesn't get saved in Live Preview. It works in Reading mode though, so it's not a big deal - I just thought to report it in case it's something simple :)

**Comment by valentine195** [comment]
Is this for blockquote style or codeblock style?

**Comment by VeroVerro** [comment]
Codeblock style - thanks for looking into it and good luck!

**Comment by nousernameavailableanymore** [comment]
I just ran into the same issue.
Apart from not retaining the "checked" status, it also doesnt seem to apply the "normal" checkbox css (in this case strikethrough).

I would really be awesome if it was possible to fix this, as admonitions is awesome with multiple columns for large amounts of checkboxes.

![image](https://user-images.githubusercontent.com/45376324/158086581-9a070e7a-5ef2-4188-b2db-a9151cb9401a.png)

**Comment by valentine195** [comment]
I recommend using the new Obsidian Callout core feature available in the insider build if you need checkboxes inside callout boxes. Because it is tightly integrated, it does not have some of the issues that Admonitions has to work around.

**Comment by nousernameavailableanymore** [comment]
Why was this closed?
Checkboxes still do not work in callout admonitions.

Was this tested / confirmed that checkboxes would work in callout boxes before closing?

**Comment by valentine195** [comment]
If checkboxes do not work in callouts, you need to submit a bug report on the Obsidian forums.
