### ISSUE TITLE
linked mention of other pages in admonition code block not detected as links for each backlinks of these mentioned pages

### ISSUE THREAD

**Issue by haroldsnyers** [valentine195/obsidian-admonition#168]
When you have links to other pages in admonition code block, these are not well processed by the backlink process. 
For example, I have a page with an admonition block that links to page A. The link on preview works well but when I go to the page of A, the page with the adm is seen as unlinked (we can for instance see [[A]] and it proposes to link that instance of A again to create link and so forth in a loop. Is there something you can do about it such that the links in the preview backlinks are correctly processed in admonition code blocks?

**Comment by valentine195** [comment]
Hi, please see #144.
