### ISSUE TITLE
Tabbing dont work

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#17]
Hey, it's me again.. :)

I encountered that <tab>-ing wont work like outside the codeblock:
![image](https://user-images.githubusercontent.com/61796661/116532692-d08d6480-a8e0-11eb-884f-7a8d531d6ac0.png)

It would be nice to get the nice fluent feeling like outside the codeblock where the next item is intended.

![image](https://user-images.githubusercontent.com/61796661/116532794-f450aa80-a8e0-11eb-9f7e-1abae3ead754.png)
 
Which results to:

![image](https://user-images.githubusercontent.com/61796661/116532819-fca8e580-a8e0-11eb-813f-11e5f7ef3a33.png)

**Comment by valentine195** [comment]
This actually does work for me with the [Outliner](https://github.com/vslinko/obsidian-outliner) plugin from @vslinko installed. Try it out!

**Comment by TobiasKlosek** [comment]
Thanks, will try it out!
