### ISSUE TITLE
[Bug]Updating the Markdown LinkName Does Not Update Links in Admonition Blocks

### ISSUE THREAD

**Issue by BrandonSLockey** [valentine195/obsidian-admonition#173]
Step1: We want to update Link Name (highlighted)

![image](https://user-images.githubusercontent.com/72495991/152677888-aaaf6bc8-06a1-450e-919b-86fbd6e6ca9a.png)

We Change the Name. 
![image](https://user-images.githubusercontent.com/72495991/152677899-ad37473c-cea9-406d-a60a-2e10e5be05a7.png)

We Expect Links to Be Updated.
Result:
Links are Not Updated in Admonition Blocks
![image](https://user-images.githubusercontent.com/72495991/152677915-a25b503e-f40e-40d2-9a21-19cdb48f66bb.png)

Great plugin, big fan, just pointing out this bug.

**Comment by valentine195** [comment]
Thanks :) Merging this with #144.
