### ISSUE TITLE
Can't load plugin 6.10.1 on Mac.

### ISSUE THREAD

**Issue by Neal0408** [valentine195/obsidian-admonition#174]
My computer is MacOS 10.15.7, I installed the latest plugin in the community.But loading of the plugin is failed.
I tried the previous version until 6.8.0. Versions before 6.8.0 can be loaded normally.
Can anyone help me this problem?

**Comment by valentine195** [comment]
Hmm. I use a Mac and it loads fine for me. Can you run the debug command from the obsidian command pallet and paste it’s output?

**Comment by Neal0408** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/37592164/152928640-e323a763-0785-4573-8cbd-6ddd6be86ce1.png">

**Comment by valentine195** [comment]
Thanks. I meant the Debug command in the Command pallet, but that helps too. What is your obsidian version and installer version?

**Comment by valentine195** [comment]
https://user-images.githubusercontent.com/38669521/153007329-309ef522-8fbe-48ff-aacf-9beef5665190.mp4

**Comment by Neal0408** [comment]
oh, it's solved. my obsidian version was v0.12.93. I even don't know there is a new version, after updating the obsidian to v0.13 plugin is loaded successfully.

**Comment by Neal0408** [comment]
oh, it's solved. my obsidian version was v0.12.93. I even don't know there is a new version, after updating the obsidian to v0.13 plugin is loaded successfully.

**Comment by valentine195** [comment]
Great! I added some minimum Obsidian version requirements to update the plugin to prevent this in the future.
