### ISSUE TITLE
[BUG] Live Preview —  Can't select texte before a list

### ISSUE THREAD

**Issue by Mara-Li** [valentine195/obsidian-admonition#175]
**Describe the bug**
**Live Preview** : For a strange reason, I can't select the first sentence after a bullet number (as `1`, `2`..). See Loom video for concize bug. 
The note need to have a *admonition* in it. 

**To Reproduce**
1. Create a admonition
2. Create a numbered list
3. Try to select the first sentence after the list number.

**Log** 
/

**Screenshots**
https://www.loom.com/share/a7454ea56cee4b10992fa455bfe4f5c2

**Desktop:**
 - OS: Windows 11
 - Obsidian Version : v.0.13.23
 - Plugin version : 6.10.1

**Additional context**
- [x] Live Preview
- [x] I already disabled every other plugin and css snippet.

**Comment by valentine195** [comment]
I'm sorry, I can't tell a difference between with and without in your video.
