### ISSUE TITLE
Image embeds not rendering in live preview

### ISSUE THREAD

**Issue by mgmeyers** [valentine195/obsidian-admonition#179]
It seems that images embedded in admonitions do not display in live preview. See this screenshot for an example:

<img width="941" alt="Screen Shot 2022-02-09 at 9 20 44 PM" src="https://user-images.githubusercontent.com/2694747/153342774-0b354c7f-9ba9-4f1b-88a4-82cd1244ccf7.png">

**Comment by I-Pch** [comment]
Ah yes, I can confirm (on Mac, at the very least - Obsidian `0.13.24`) 😊 ...
This seems to work with block code admonitions but not with  MS Doc Syntax

**Comment by valentine195** [comment]
This should be fixed in v7.0.0... please re-open if it is not.
