### ISSUE TITLE
Feature request: Octicons

### ISSUE THREAD

**Issue by defaltus** [valentine195/obsidian-admonition#181]
Would it be possible to support Octicons as alternative icons? As described [here](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons).

**Comment by valentine195** [comment]
I'm not sure I want to bundle another font pack with the plugin, as it is already quite large due to Font Awesome being bundled. I may give the option to download additional font packs in settings. Let me think about this.

**Comment by valentine195** [comment]
You can now download additional icon packs in settings.
