### ISSUE TITLE
Mathjax formula in Live Preview Mode is huge

### ISSUE THREAD

**Issue by faro1219** [valentine195/obsidian-admonition#189]
Hi! I just found that the spacing between the Mathjax formula in Live Preview is much larger than that in preview mode. My admonition version is 6.12.0, and the obsidian version is v0.13.23.

Live Preview mode
![image](https://user-images.githubusercontent.com/31923679/154820907-e84f9c9d-4a46-4249-a80d-e028edc422d8.png)

Preview mode
![image](https://user-images.githubusercontent.com/31923679/154820918-181b0842-74e5-4333-b13c-c466dfda84a7.png)

**Comment by valentine195** [comment]
Hi... I don't see this issue. Can you recreate it in the help vault?

**Comment by faro1219** [comment]
I can recreate it with a new test vault. I only installed the admonition plugin.  BTW, I am using $$ $$ for the mathjax formula. 

Live Preview
![image](https://user-images.githubusercontent.com/31923679/154830606-4a41d00b-5e97-4719-bc07-de29d669baa2.png)


Preview
![image](https://user-images.githubusercontent.com/31923679/154830552-ff7448b2-2bd3-4bce-8434-e832da126776.png)
