### ISSUE TITLE
Improve Appearance of "Insert Admonition" Command Dialog 

### ISSUE THREAD

**Issue by juicybox** [valentine195/obsidian-admonition#190]
Please improve the appearance of the **Insert admonition** command dialog window.

![Screenshot_1](https://user-images.githubusercontent.com/3801775/155027078-1c77c6d1-1def-46c7-abf9-3955e698d151.png)

## Problems

- dropdown to small (width)
- icons are overflowed by text
- new users have too many possible options (might be confusing, what to use..)
  - other (common) workflows
  - doesn't fit into personal scheme
    - would like to use only my types 
    - guidelines (personal/company/…)
  - decluttering
    - minimalism
    - focus

### **Appearance Improvement**: Move & Align Icons on the left side (fixed width)

![Screenshot_3](https://user-images.githubusercontent.com/3801775/155029246-23e765da-8396-4e9d-aa9d-a4beb94dc47f.png)

### **Appearance Improvement**: full Input width for the dropdown (or even better with auto sizing)

![Screenshot_2](https://user-images.githubusercontent.com/3801775/155029410-ca34e980-3c18-4f9f-a4e7-27a4a957b28d.png)

### **Add Configuration Option**: Disabled predefined/default options

**Add a checkbox in the configuration, to disable**
  - **all (keep it simple)** predefined Admonition types
  -  or any user selected (advanced) predefined Admonition types

The user can add custom types, only the required or common used types by themselves.
- it would be great to disabled the options at least in the select dropdown (the background logic can be the same)
- or add data-Attributes to the selection Dropdown (for custom CSS, to hide Options from the View)

![Screenshot_4](https://user-images.githubusercontent.com/3801775/155030341-59f81b23-9661-4980-bcf2-6f7e90e28756.png)

**Comment by valentine195** [comment]
> dropdown to small (width)
> icons are overflowed by text

Does this happen for you on the default theme? I think this might be a theme issue.

Help vault appearance:
![Obsidian_Fg2hBMZXry](https://user-images.githubusercontent.com/38669521/155744721-3611d973-fc46-4d33-9aae-49d763cd2723.png)

I did make the suggester full-width, though.

**Comment by juicybox** [comment]
@valentine195 Good point, it seems that an issue is related to the theme I'm using "**Minimal Theme**"
> ~icons are overflowed by text~

- the related problem is "icons are overflowed by text" **--> Theme: "Minimal" Issue**  
https://github.com/kepano/obsidian-minimal
    - ~Appearance Improvement: Move & Align Icons on the left side (fixed width)~

### Some Tests with other common Themes

#### Default Theme 🆗 

![Pasted image 20220226030109](https://user-images.githubusercontent.com/3801775/155825050-05eade13-a104-4965-a5b8-156563ee9109.png)

#### Depp Work Theme 🆗 

![Pasted image 20220226030213](https://user-images.githubusercontent.com/3801775/155825097-ff235227-23e3-40fe-bf0d-d8075201140d.png)


#### Nord Theme 🆗 

![Pasted image 20220226030246](https://user-images.githubusercontent.com/3801775/155825081-ebf8993a-a274-4812-817a-c6c4960736b0.png)


#### Minimal Theme 🐛 

![Pasted image 20220226030350](https://user-images.githubusercontent.com/3801775/155825125-f14bde5a-0e16-4a1f-9d97-6eb51bb782e2.png)

---

- Obsidian Version : 0.13.26
- Admotion Version 6.12.1
- Minimal Theme Version: 5.1

**Comment by valentine195** [comment]
Okay, I'm going to consider this closed then.

**Comment by juicybox** [comment]
> Okay, I'm going to consider this closed then.

Thanks!

![image](https://user-images.githubusercontent.com/3801775/156637157-985a6f18-05f1-450f-8d30-4f533288305d.png)
_Minimal Theme Version: 5.1_
