### ISSUE TITLE
Different HTML output with ```ad-note vs Microsoft syntax

### ISSUE THREAD

**Issue by phillipjohnston** [valentine195/obsidian-admonition#192]
Hello,

I recently switched some of my writing from using the markdown syntax to using the Microsoft syntax. When I look at the rendered output within obsidian, they look equivalent. However, I generate the HTML for publication on a website (not using publish) - in the generated HTML output, the Microsoft syntax generates a blockquote instead of the proper admonition HTML.

Is there a functional difference between the two that is causing this behavior?

**Comment by valentine195** [comment]
> However, I generate the HTML for publication on a website

How are you doing this?

**Comment by phillipjohnston** [comment]
https://github.com/OliverBalfour/obsidian-pandoc, which for HTML uses some built-in support instead of pandoc itself.

**Comment by phillipjohnston** [comment]
Using Obsidian's internal renderer: https://github.com/OliverBalfour/obsidian-pandoc/blob/8229273d854461b78d8606ba4136bf8018a478fa/renderer.ts#L24

**Comment by valentine195** [comment]
I’m not sure what exactly causes the difference. I believe that should run the same post processors as the normal markdown renderer. But I believe this would actually be an issue with the Pandoc plugin.

**Comment by phillipjohnston** [comment]
Why do you believe that?

**Comment by phillipjohnston** [comment]
"I don't want to deal with it" is a fine answer - I'm happy to continue to use markdown syntax because it works great - but I don't personally understand how a call to Obsidian's MarkdownRenderer.renderMarkdown function makes it that plugin's issue. It's not doing anything with admonitions.

**Comment by phillipjohnston** [comment]
Actually, I can confirm the same behavior occurs if you use Obsidian's native "Export to PDF" feature. If you use an admonition code block, the admonition renders. If you use the MS syntax, it renders as a block quote.

<img width="558" alt="Screen Shot 2022-02-24 at 10 39 42" src="https://user-images.githubusercontent.com/1709063/155586862-516563bf-fb9a-4d2d-a266-3f90550a1a3c.png">
<img width="643" alt="Screen Shot 2022-02-24 at 10 39 57" src="https://user-images.githubusercontent.com/1709063/155586873-d3704144-a9a5-46d7-8679-a9068625adee.png">

**Comment by valentine195** [comment]
>  I don't personally understand how a call to Obsidian's MarkdownRenderer.renderMarkdown function makes it that plugin's issue

Just because the codeblock syntax isn't doing anything special, really. The PDF issue does point it back at me, though 😄 I will take a look. Thanks for the investigation!

**Comment by valentine195** [comment]
Okay, I figured out why they are behaving this way. It seems there are instances where the markdown post processors will not receive the correct contextual section information. Bad news is, it's not easy to get the text content of what I want to render, then :) I'll poke at it, but I also asked the Obsidian dev if he could just include it.

**Comment by phillipjohnston** [comment]
Thanks for looking into it and the update. (Is access to that code something you get as a big time plugin developer?)

**Comment by valentine195** [comment]
> Is access to that code something you get as a big time plugin developer?

Nope, it's in the front end developer tools, just minified :)

I actually have fixed this. Was just about to push the update.

**Comment by phillipjohnston** [comment]
Right on!
