### ISSUE TITLE
Question: How to query and display all the specified type of admonition block in my notes?

### ISSUE THREAD

**Issue by Beau-Yang** [valentine195/obsidian-admonition#193]
I have created many admonitions in my notes. Is it possible to query and display all the specified type of admonition block such as ad-note so that all the important information can be shown in one place? That can really help us to use the admonition in a better way.

 (By the way, the admonition itself is very nice and helpful, thx

**Comment by valentine195** [comment]
You can do this with the Obsidian query block:

````
````query
/```ad-note[\s\S]+?```/
````
````

I also recommend using [this](https://github.com/nothingislost/obsidian-query-control) plugin, which will allow you to render the results.

![image](https://user-images.githubusercontent.com/38669521/156580552-ff7bbc24-e833-4254-ac86-e103847b4368.png)
