### ISSUE TITLE
Image embeds not rendering in live preview (Follow up on Issue #179)

### ISSUE THREAD

**Issue by I-Pch** [valentine195/obsidian-admonition#194]
Hi there 😊 !

As I was not the OP from #179 I couldn't re-open the issue (sorry).
I'm still encountering the rendering issue of embedded images (`![[MyImage.png]]`) in `Live Preview` within MS Doc Admonitions 😇 . 

For the MS Doc syntax Admonition (`>`), the link to the image is accounted for as an outgoing one (so there's that already 😊 ) but the image in itself is just not displayed once we stop editing the Admonition. It seems to be displayed while editing the Admonition though (i.e.: before the Admonition gets fully rendered) 😊 ...

<img width="462" alt="Bug Img Live Prev - While editing" src="https://user-images.githubusercontent.com/77828085/155881851-8b2b7458-2fd2-44f1-a20d-3c1f9af92b42.png">

Final test results 👇  
<img width="1436" alt="Bug Image Live Prev - MS Doc Syntax" src="https://user-images.githubusercontent.com/77828085/155881598-4f200bfc-b947-423f-8cde-233ee4a5caf9.png">

Tested on: Mac -> Obsidian `0.13.26` (Default Theme) -> Admonition `7.0.2`

**Comment by valentine195** [comment]
Obsidian has implemented MSDoc-syntax callouts to the latest insider build as a core feature, so this syntax has been removed from Admonitions.
