### ISSUE TITLE
Replace Block With HTML

### ISSUE THREAD

**Issue by huangziwei** [valentine195/obsidian-admonition#195]
Hi,

Issue #52 mentioned that there's "Replace Block With HTML" function in 6.0.0, but I cannot find it anymore in 7.0.2. 

I tried 6.0.0 and I could find the command but it also didn't work. Has this functionality been removed?

**Comment by valentine195** [comment]
Yes, this broke mobile compatibility so I removed it. Sorry for the confusion.

**Comment by huangziwei** [comment]
Is there still a way to achieve this, though? I am using a static site grantor to make a html version of my vault, and would like to include Admonition block.
