### ISSUE TITLE
Outgoing links not updated

### ISSUE THREAD

**Issue by hnt4499** [valentine195/obsidian-admonition#196]
When referencing another doc inside an Admonition block, the Backlinks / Outgoing links show weird behaviors.

For example:
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/45118728/156184487-744684d6-c0dd-48c5-ba18-e16d303b9cf1.png">

In this example, when referencing non-existent docs, `first` does not show up in the outgoing links tab while `second` does.
At the same time, when referencing existing docs, the `Shortcuts` in the second Admonition block results in an unlinked mention while the normal `Shortcuts` at the end (without Admonition) results in an outgoing link as expected.

Moreover, all seem to be correctly recognized in the graph view.

**Comment by valentine195** [comment]
In general, if you need links to show up in graph view and the outlinks plugin, I recommend using the MS doc syntax. 

Links inside of code blocks are not parsed by Obsidian. I can mitigate that a little bit but it is difficult to keep the cache in sync. Also see #144
