### ISSUE TITLE
Nesting MS Doc Syntax (>) Admonitions ?

### ISSUE THREAD

**Issue by I-Pch** [valentine195/obsidian-admonition#197]
Hi there 😊 !

Not sure if this would qualify as a `Feature Request` or a `Bug Report` but today I tried to nest MS Doc Syntax Admonitions (`> `) ... and I was very pleased to discover it partially works already 😁 ...

The only trouble is that everything within the nested admonitions doesn't seem to be correctly rendered (except for non-formatted text and Dataview inline fields) 😔  ...

As maybe, I'm just trying to do something the plugin is not ready for (potentialy yet 😇 ) I just thought I'd mention it here (as it would be a nice feature to have, if it's possible to implement it) 😊 ...

I used 2 Admonitions for comparison purpose : A flat one and the same flat one with 2 different nested ones (so no nested in already nested)

The markdown I used for the flat one is : 
```
> [!success: Flat Admonition ]
> [[Winter#Winter|☃️ Winter]] ･ <progress value="0.7978" max="1"></progress> 79.78% ⦗+71d ⦘  ⪼  🌿 Spring ⦗-19d ⦘
> 
> [[Waning Crescent#Waning Crescent|🌘 Waning Crescent]] ･ :ril_percent::rif_lightbulb: <progress value="0.04" max="1"></progress> (moon_illuminated::4)%
> 
> 🌑 Lunation (lunation::1226) ･ <progress value="1" max="1"></progress> (lunar_day_prog::100)% ･ Lunar Day (lunar_day::28.8) ⦗/(lunar_day_length::28.8)⦘ 
```
 
And for the other flat one  + 2 nested ones on the same level : 
```
> [!bug: Nested Admonition ]
> Link to an **existing** file -> [[2022-02-28#2022-02-28|yesterday]]
> > [!note]
> > [[Winter#Winter|☃️ Winter]] ･ <progress value="0.7978" max="1"></progress> 79.78% ⦗+71d ⦘  ⪼  🌿 Spring ⦗-19d ⦘
> > Link to an **existing** file -> [[2022-02-28#2022-02-28|yesterday]]
> 
> 
> > [!quote]
> > [[Waning Crescent#Waning Crescent|🌘 Waning Crescent]] ･ :ril_percent::rif_lightbulb: <progress value="0.04" max="1"></progress> (moon_illuminated::4)%
> 
> 🌑 Lunation (lunation::1226) ･ <progress value="1" max="1"></progress> (lunar_day_prog::100)% ･ Lunar Day (lunar_day::28.8) ⦗/(lunar_day_length::28.8)⦘ 
```

And here's the screenshot of the results in `Live Preview` and `Reading` 

<img width="1440" alt="Nested Admonitions (LP   Reading)" src="https://user-images.githubusercontent.com/77828085/156213668-c60ba336-9c21-41ca-a391-d7051abb5860.png">

Tested on Mac -> Obsidian `0.13.28` + Admonition `7.0.3` 😊

**Comment by valentine195** [comment]
Obsidian has implemented MSDoc-syntax callouts to the latest insider build as a core feature, so this syntax has been removed from Admonitions.
