### ISSUE TITLE
MS Syntax fails to show latex and images when exported as PDF

### ISSUE THREAD

**Issue by shodankim** [valentine195/obsidian-admonition#198]
![image](https://user-images.githubusercontent.com/66750905/156368000-aa8eb0b7-80ea-46dd-8470-413afe299163.png)

The first one was created with the MS Doc Syntax, the latter was with ```ad-note```

Would this be fixable? I have quite a bit of pages that need to be exported as pdfs so this is a huge personal issue.

**Comment by valentine195** [comment]
Obsidian has implemented MSDoc-syntax callouts to the latest insider build as a core feature, so this syntax has been removed from Admonitions.
