### ISSUE TITLE
Feature: Support more icon pack via obsidian-icon-shortcodes

### ISSUE THREAD

**Issue by aidenlx** [valentine195/obsidian-admonition#199]
I'm the dev of [Icon shortcodes plugin](https://github.com/aidenlx/obsidian-icon-shortcodes), a plugin that includes an icon manager to manage user-imported custom icons, and icon packs such as Font Awesome, Remixicon, RPG Awesome, etc. 

In the upcoming v0.7.0+, it will no longer bundle any svg icons and use lucide icons available in obsidian v0.13.27+, and provide a icon pack browser to easily download icon packs. Imported icons are stored as files in `.obsidian/icons`, so including more icons won't cause memory problem caused by loading icons in json file or [increase bundle size](https://github.com/valentine195/obsidian-admonition/issues/181#issuecomment-1048212250)

You can check here for details about its api: https://github.com/aidenlx/obsidian-icon-shortcodes#for-developer. [link favicon](https://github.com/joethei/obsidian-link-favicon) already support icon shortcodes so it might be a good place to reference code. In v0.7.0+, the api doesn't contain any breaking changes, so it's safe to develop against published version of obsidian-icon-shortcodes. 

 feel free to ask if you have any question :)

**Comment by aidenlx** [comment]
icon shortcode v0.9.0 support callout icon, closing this now.

**Comment by valentine195** [comment]
And I was just working on this last night! 😁

**Comment by aidenlx** [comment]
btw, if you are implementing a interface to manage callout icon, you can check out [getIconFromUser](https://github.com/aidenlx/obsidian-icon-shortcodes/blob/0db5a0a925fb2067d3e1dc7ac063d0edb87f91e3/src/typings/api.ts#L29-L33) method which can open a modal to prompt user for icon selection (available since v0.6.1)

**Comment by valentine195** [comment]
I just inject a detached stylesheet with the custom admonitions defined as callouts, with icons defined using an SVG tag.

**Comment by aidenlx** [comment]
I've done it in post processor, adding a mutation observer for icon injection and insert custom icon when no icon is rendered by default renderer. https://github.com/aidenlx/obsidian-icon-shortcodes/blob/04b4a8ee0ebe327c70e84c5137f0d2a4e198908b/src/post-ps/callout-icon.ts
