### ISSUE TITLE
Plugin feedback

### ISSUE THREAD

**Issue by lishid** [valentine195/obsidian-admonition#2]
Just a little concerned that this plugin is using two dozen code block IDs. I've been contacted by several plugin developers about this who believes that this doesn't seem like a good idea.

I understand that this is for convenience, but I would highly suggest to either prefix your code block id, or use a single code block id but have the type as a content parameter, like you already do with `title` and `collapse`. This would reduce the likelihood of your plugin conflicting with another, causing confusion for the user.

Let me know what you think.

**Comment by valentine195** [comment]
Yeah, I went back and forth on this before I submitted it, but when I first wrote it I just straight up copied the [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) syntax and it seemed several people in the forums were using it, so I left it as-is to prevent breaking their already written notes.

I was thinking of just prefixing the ID with `ad-` (as in, `ad-note`). Do you think that would be acceptable?

**Comment by lishid** [comment]
That could work - in fact one of our mods proposed the `ad-` prefix as a solution. In the end I think it's a balance between convenience, how good it looks in code, and how likely it's going to conflict with other plugins. I'm good as long as something is done to address the potential conflict.

**Comment by valentine195** [comment]
Okay, updated with 2.0.0.

Also, just a quick question related to this - is there an API hook for when a plugin is updated (as opposed to just loaded / installed)? This could be used, for instance, to alert users to syntax changes.

Anyway, thanks for the feedback.

**Comment by ryanjamurphy** [comment]
Thanks for being so responsive (and responsible) on this front, @valentine195! 

I'm not sure on the update hook, but you could do a staged deprecation: continue to recognize the previous syntax for an update or two, but present a message in the rendered blocks warning users about what the new syntax should be.

**Comment by valentine195** [comment]
A staged deprecation would work, but I think in this instance it was better to just rip the band-aid off :grin:
