### ISSUE TITLE
Title cuts off after second colon.

### ISSUE THREAD

**Issue by Trinsec** [valentine195/obsidian-admonition#20]
Heya! Cool plugin! I've noticed a li'l bug.
If you do this:
````
```ad-note
title: foo:bar
baz
```
````
everything after the second : gets cut off in the title. In this case 'bar' isn't visible in the preview.

(I quickly updated to 3.3.0 to check if this bug is still present. It is. But I noticed another bug after updating: In the examples in the Admonition Settings, the icons are centered and above the titles. Thankfully they render fine in the actual notes themselves.)

**Comment by valentine195** [comment]
Thanks for letting me know. These issues are fixed in 3.3.1.
