### ISSUE TITLE
Reduce Margins (snippet didn't work)

### ISSUE THREAD

**Issue by ReaderGuy42** [valentine195/obsidian-admonition#204]
Sorry to be a bother, and thanks for the snippet you gave me in the other issue https://github.com/valentine195/obsidian-admonition/issues/200 but that didn't work. I also just updated the plugin to the most current version but the margins are still pretty big.

Any other ideas?
Thanks!

**Comment by valentine195** [comment]
Please stick to 1 issue for discoverability!
