### ISSUE TITLE
Is it possible to change color palette for all defined types?

### ISSUE THREAD

**Issue by HideoKun** [valentine195/obsidian-admonition#205]
Hi! 

I would like to change all the colors for any 'ad-[type]' variant, but I am not able to find palette definition in your repo :)

How to find them? Thanks :)!

**Comment by valentine195** [comment]
Default admonition colors are defined in [this file](https://github.com/valentine195/obsidian-admonition/blob/c5bef6c7d5f04fdfcbb838fcfa3d156719c058b6/src/util/constants.ts#L21) as an RGB triad. 

The title element is that same color at 10% alpha (see [here](https://github.com/valentine195/obsidian-admonition/blob/c5bef6c7d5f04fdfcbb838fcfa3d156719c058b6/src/assets/main.css#L36))

**Comment by HideoKun** [comment]
Could we extract those colors to separate file - 'theme.css' or sth like that - to make it easily adjustable? I would like to use Nord-Theme instead of default colors. If so, this opens possibility to use this plugin as a core part of obsidian themes. It would be cool if themes could overload admonitions with their own css vars :)

**Comment by valentine195** [comment]
They can - check out Ebullientworks. 

The admonition css just looks for the `--admonition-color` CSS variable. You can you override that in a theme, and the admonition will use it instead. It just has to be defined as an rgb triad (`--admonition-color: 220, 56, 36` or something)
