### ISSUE TITLE
Bug: MDS admonitions without title

### ISSUE THREAD

**Issue by Cammagno** [valentine195/obsidian-admonition#206]
> [!quote:]
> This admonition won't have a title!

This does not work for me, it shows the dafault title

**Comment by I-Pch** [comment]
Hi @Cammagno 😊 ... I think you need a space after the colon (`:`)  😊 

This : 
```
> [!quote: ]
> This admonition won't have a title!
```

Should give you this : 
<img width="730" alt="Ad-Test" src="https://user-images.githubusercontent.com/77828085/156899312-b97bdc4c-7845-4ddd-83fc-9b805d92546f.png">

**Comment by Cammagno** [comment]
> I think you need a space after the colon (`:`)

Hi, thanks for your reply :)

I've tried also with a space (see picture below) but it still puts the default title to it

![Admonition](https://user-images.githubusercontent.com/95725064/156900912-0d23cd71-488a-4461-9e9e-f3f210650137.PNG)

**Comment by valentine195** [comment]
Have you updated the plugin recently? I just fixed this the other day.

**Comment by Cammagno** [comment]
> Have you updated the plugin recently? I just fixed this the other day.

this is my version: 7.0.4

![Admonition2](https://user-images.githubusercontent.com/95725064/156902272-c5310ab3-b0c6-46a2-a478-358cb1ecf856.PNG)

**Comment by Cammagno** [comment]
> Have you updated the plugin recently? I just fixed this the other day.

I've now updated to 8.1, but still I can't get a title-less Non-code block Admonition

**Comment by valentine195** [comment]
Are you on insider? Obsidian has implemented their own version of Admonitions (called callouts), so the MSDoc admonition syntax has been removed. I do not believe there is a way to not have a title with the native callouts.

**Comment by Cammagno** [comment]
> I do not believe there is a way to not have a title with the native callouts.

Ok, thanks, so to have a title-less admonition I need a codeblock one, got it.
