### ISSUE TITLE
Microsoft syntax not working for indented items?

### ISSUE THREAD

**Issue by fgimian** [valentine195/obsidian-admonition#207]
Hey there folks, thanks so much for this wonderful extension.  I've discovered one little issue with the Microsoft syntax.

Given this Markdown:

````markdown
Hello there, let's test the Microsoft syntax:

```ad-note
This is a code block note that's not intended, it works well!
```

> [!note]
> This is a Microsoft note that's not indented, it works great!

OK, now let's get into a list:

1. This is the first item

    ```ad-note
    This is a code block note that's indented, it still works!
    ```

2. This is the second item

    > [!note]
    > This is a Microsoft note that's indented, it's busted :()

3. And another
````

The output is as follows:

![image](https://user-images.githubusercontent.com/1811813/156912765-67b1d8c8-fbb5-44e0-a2d4-669b46063f4e.png)

As you can see, the Microsoft syntax doesn't seem to work on indented notes.  I've used a 4 space indent for this file.

Any ideas?
Fotis

**Comment by valentine195** [comment]
Obsidian has added MSDoc-syntax callouts to the insider build as a core feature. I am tagging this as wontfix.
