### ISSUE TITLE
[Question] Possiblity to edit content when clicking on admonition (instead of edit icon)

### ISSUE THREAD

**Issue by vii33** [valentine195/obsidian-admonition#208]
Hi, I love this plugin, thanks a lot for creating it! 😍
I would have one question, though: When I want to edit an admonition then I have to click on the small edit icon (upper right corner). This is a bit cumbersome. A leaner process could be to just click on the main content (similar to the code blocks). 

Can I achieve this behaviour somehow?

**Current behaviour:**
![grafik](https://user-images.githubusercontent.com/1887246/156926284-d9365c0f-cd42-4a7c-86e4-bb892f82e40e.png)

**Requested behaviour:**
![grafik](https://user-images.githubusercontent.com/1887246/156926348-8485a783-5367-41d0-97ea-58d6f425dc8f.png)
---vvv---
![grafik](https://user-images.githubusercontent.com/1887246/156926361-46bd5a33-d1ff-43d0-9f99-8533dc4dbda0.png)

-----------------------------

**Similar to code blocks behaviour:**
![grafik](https://user-images.githubusercontent.com/1887246/156926464-f3ea9a01-be30-422e-b5c3-c8161fd7cfd3.png)
---vvv---
![grafik](https://user-images.githubusercontent.com/1887246/156926469-f94963e5-0c56-44f6-9ce9-ede7a5249b92.png)

**Comment by tangor86** [comment]
I have the same q too... it is inconvenient to click the icon in the right to edit instead of just clicking once in any place of the block, as it is done for the code block...

**Comment by valentine195** [comment]
This is actually pretty tricky and will require using undocumented parts of the API. Sorry!
