### ISSUE TITLE
Mathjax in admonition, too much blank space.

### ISSUE THREAD

**Issue by Ampa** [valentine195/obsidian-admonition#21]
``` ad-example
How many ways can we arrange a dog, a cat, and a pig?
$$n=3$$
$$3!=3×2×1=6$$
```
The 2 mathjax blocks end up very widely spaced.

**Comment by valentine195** [comment]
Hmm, it looks identical to the way Obsidian displays it natively to me:

<img width="1031" alt="Screen Shot 2021-04-29 at 8 39 06 PM" src="https://user-images.githubusercontent.com/38669521/116634807-1bcc6500-a92b-11eb-8f3b-5d7f8856e8cd.png">

**Comment by TobiasKlosek** [comment]
@Ampa you might trying out inserting [Align-Environments](https://www.overleaf.com/learn/latex/aligning_equations_with_amsmath) for typing formulas.

**Comment by Ampa** [comment]
My apologies. You are correct!

It looked so big I assumed it was a bug!
