### ISSUE TITLE
Feature: open admonition in notes on print

### ISSUE THREAD

**Issue by Jason11ookJJ** [valentine195/obsidian-admonition#210]
Currently when exporting to pdf, all the admonition are closed if the collapse is set to `close`, as a result, the text under it cannot be seen.

![image](https://user-images.githubusercontent.com/50993239/157279533-5df2a3ae-2503-493d-9d07-6346228f1d4b.png)
For example, I cannot see the answer

Is it possible to add a feature so that the admonition will open on export? Thx.

**Comment by valentine195** [comment]
The Print to PDF function renders the note in a separate process, this would be difficult if not impossible to do.
