### ISSUE TITLE
Rendering of Footnotes

### ISSUE THREAD

**Issue by AtrusRiven** [valentine195/obsidian-admonition#211]
First of all: Thanks for the great plugin!

Would it be possible to change the rendering of footnotes `^[footnote text]`? At the moment, footnotes are rendered inside the admonition box. I’d like to have the possibility to optionally activate the rendering of footnotes at the end of the page.

Thanks a lot!

**Comment by valentine195** [comment]
This is getting tagged as wontfix because Obsidian has added callouts as a core feature to the latest insider build. If you need links or footnotes to work without callouts, you should use that syntax.
