### ISSUE TITLE
Admonitions not working with sliding windows in Obsidian Publish

### ISSUE THREAD

**Issue by Tomagori** [valentine195/obsidian-admonition#217]
I got Admonitions to work in my Obsidian Publish setup, but I've stumbled upon an issue: Admonition CSS only loads when the page with the admonition on it is the "main" page, so either if sliding windows is _off_, or if it's the _first window_ when sliding windows is _on_. When sliding windows is _on_ and the page with the admonition is in the _second, third or a later window_ (so one of the windows that slide in from the side), the admonition just appears as a grey box to me.

**Comment by valentine195** [comment]
Thanks for letting me know. Obsidian has added Callouts to the latest insiders build that work natively on publish, so I will not be working on the publish feature going forward.
