### ISSUE TITLE
Bug: image inside collapsed callout does not render properly

### ISSUE THREAD

**Issue by Cammagno** [valentine195/obsidian-admonition#219]
Not sure if this is a problem due to Admonition itself or Obsidian Callouts (now it's hard to me to understand which is doing what), but if I put an image inside a callout collapsed by default, it does not render properly, its size is shown instead of the image itselfe (see attached picture)
This happens only if the callout is collapsed by default (- after the ])
![Admonition](https://user-images.githubusercontent.com/95725064/158369744-8286b98d-aafc-4e47-9db0-2b5eb8cb9675.PNG)

**Comment by valentine195** [comment]
Does this happen with Admonitions turned off? You’ll have to close and reopen the note.

**Comment by Cammagno** [comment]
> Does this happen with Admonitions turned off? You’ll have to close and reopen the note.

Yes.
So it's due to Callouts .
It was easy to understand if it was Admonition's fault, after all :D
