### ISSUE TITLE
Wrong spacing with Links and Mathjax inside title

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#22]
Hey, its me again! :)

First of all, thanks for this speed of improving!

I found some issue (i think with the newest update, because this worked properly in the last versions i guess) which shows an wrong behaviour regarding the spacing between `[[Links]]` and `$formula$` or `$$formula$$` .. so mathjax in general.

![image](https://user-images.githubusercontent.com/61796661/116674739-4eb33f00-a9a5-11eb-89ca-ba37e7421c1c.png)

This results to:

![image](https://user-images.githubusercontent.com/61796661/116674782-5b379780-a9a5-11eb-85b9-b08f2e8d3b9c.png)

or without the Link and just the inline mathjax:

![image](https://user-images.githubusercontent.com/61796661/116675576-41e31b00-a9a6-11eb-8d19-e9e37020d16b.png)

so the spacing is lost around these.

**Comment by valentine195** [comment]
Fixed in 3.3.3
