### ISSUE TITLE
new update breaks 'tldr'

### ISSUE THREAD

**Issue by Oblique82** [valentine195/obsidian-admonition#220]
Hi for whatever reason I have a lot of daily notes with the following code

ad-tldr
title: Daily Review

the 'tldr' does not work - it used to, and rendered the same as 'abstract' which works

Any way to make it continue to work or just search and replace the entire vault's "tldr' with "abstract"?

**Comment by valentine195** [comment]
What version of Obsidian and Admonitions are you on? It works for me (running Obsidian 0.14 and Admonitions 8.2.1)

![image](https://user-images.githubusercontent.com/38669521/158628456-199a6258-ea74-400b-98c8-a800ee675c42.png)

**Comment by valentine195** [comment]
I actually may have found what caused this issue for you - if you can update to 8.2.2, does it still occur?

**Comment by Oblique82** [comment]
Community plug-in updates is still stuck on 8.2.1 - cannot update via obsidian

**Comment by Oblique82** [comment]
ok this is fixed with latest update - thanks!
