### ISSUE TITLE
Nesting Code-block Admonitions - Custom Callouts troubles...

### ISSUE THREAD

**Issue by I-Pch** [valentine195/obsidian-admonition#227]
Hi there 😊 !

I was again trying to nest 2 admonitions/custom callouts  but I'm having some troubles with that 😊 ...

The admonitions I created through the plugin and used for my tests here are both supposed to display no type and not title (which works perfectly with the native Obsidian Callout syntax when I'm not trying to nest them in a note 🙌 )

Here are the things I tried on `Mac` + `Obsidian v0.14.2` + `Admonition 8.2.3` (No Community theme)

## 1. Nested Code-Block Admonitions
🟠  It seems to fail in `LP` : The closing ` ````` ` of the 1st level code block admonition seems to be ignored when rendered in LP.
I've tested this with the code block example from the README and my admonitions/custom callouts created through the plugin with the same result 😊 
``````
`````ad-note
title: Nested Admonitions
collapse: open

Hello!

````ad-note
title: This admonition is nested.
This is a nested admonition!

```ad-warning
title: This admonition is closed.
collapse: close
```
````

This is in the original admonition.
`````
``````
Which looks like this in `LP` 🟠 
<img width="661" alt="README Admonition - LP" src="https://user-images.githubusercontent.com/77828085/159242629-2d3e6f68-d670-4370-a7ba-a261ddaf14aa.png">

And like this in `Reading` 🟢  
<img width="661" alt="README Admonition - Reading" src="https://user-images.githubusercontent.com/77828085/159243106-962deba3-989f-49c4-a737-4c496f73cb3e.png">

And for the Admonitions I created through the plugin
(The setting `No Admonition Title by Default` is toggled `ON` for both `ad-nav` & `ad-ephemeris`)
`````
````ad-nav
Something...

And another Admonition...
```ad-ephemeris
Something else
```
Back to the 1st level admonition ...
````
`````

It gives me this in `LP` 🟠 
<img width="661" alt="Nested code block Admonitions - LP" src="https://user-images.githubusercontent.com/77828085/159244108-5d906702-d03d-4a61-aa4f-1409c6c2c04f.png">

And this in `Reading` 🟢 
<img width="661" alt="Nested code block Admonitions - Reading" src="https://user-images.githubusercontent.com/77828085/159244440-a03abf3a-2357-422d-891b-bd50abd392e6.png">

## Note
I'm a big fan of the new native Obsidian callouts syntax and I don't wish to use code-block admonitions 😊.
Since the now gone MS Docs syntax was introduced in the plugin, I never used any other available syntax 😊, so I'm all for creating custom callouts through the plugin and using them with the native Obsidian callouts syntax. 
I ran the tests with the code blocks Admonitions to see if what I wanted to do was somehow feasible or not... 
And the result I'm looking for here using my custom callouts with the native Obsidian callouts syntax in `LP` is indeed the one I get in `Reading` with the nested code block admonitions 😇      

## 2. Nested Admonitions using the native Obsidian Callouts syntax
```
> [!nav] 
> Something
> 
> And another "Custom Callout"
> > [!ephemeris] 
> > Something else...
> 
> Back to the 1st level admonition ...
```
It definitively works in `LP`  and `Reading` with the exception that, for some reasons, the toggled `ON` setting `No Admonition Title by Default` seems to be ignored for the nested Admonition/custom callout (`> > [!ephemeris]`) but it works for the 1st level  Admonition/custom callout  (`> [!nav]`) without any problem ... 
(The setting is also taken in to account when those 2 custom callouts (using the native Obsidian callouts syntax) are not nested and placed in my notes one after the other)
<img width="659" alt="Custom Callouts - Obsidian Syntax - LP" src="https://user-images.githubusercontent.com/77828085/159249666-e8352f75-c9a1-454a-8752-614840dc0295.png">

## After all this...
As I'm trying to get this result 👇 (`Reading` + `code block admonition`)
<img width="661" alt="Nested code block Admonitions - Reading" src="https://user-images.githubusercontent.com/77828085/159251447-13943e3f-0193-4557-86d5-6e0241ec4d59.png">

... **but with the native Obsidian callouts syntax** ... I guess my question is : 
Would there be any way to force the `No Admonition Title by Default` for the nested custom callouts to be taken into account by Obsidian ? 
Couldn't this setting be added to the Admonition CSS snippet so it potentially override the Obsidian callout CSS ? 😇
(same goes for the drop-shadow 😇 ... which seems to work in block code admonition but not with Obsidian callouts syntax, as mentioned in #222 ) 

I have no idea how to do that 😅 ... hence why I'm here 😊...

Once again, I'm sorry for the length 😇 ... But I thank you very much in advance for any help 😁 !

**Comment by valentine195** [comment]
Can you make multiple issues for the different problems?

**Comment by I-Pch** [comment]
Sure 😊 !

but what do you mean ? 

One issue for the nested code block problem, one for the nested custom callouts and one for the drop-shadows ?

**Comment by valentine195** [comment]
> One issue for the nested code block problem, one for the nested custom callouts and one for the drop-shadows

This one, but the drop shadow issue already exists, no need to make another one 😃

**Comment by I-Pch** [comment]
Ok 😁 ! I'm on it 😁 !
