### ISSUE TITLE
Pictures wont render in 3.3.3

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#23]
Hey,

the last update broke somehow the picture-rendering. For example:

![image](https://user-images.githubusercontent.com/61796661/116735186-77abf200-a9ee-11eb-8277-681825a401fa.png)

results to:

![image](https://user-images.githubusercontent.com/61796661/116735202-7c70a600-a9ee-11eb-9656-7508da41fe6c.png)

**Comment by valentine195** [comment]
Interesting... seems waiting on the Markdown Renderer to finish causes this. Should be fixed in 3.3.4.
