### ISSUE TITLE
Is it possible to put different style in each admonition type?

### ISSUE THREAD

**Issue by Alexnoj** [valentine195/obsidian-admonition#231]
Is it possible to put different style (form, color etc) in each admonition type and not global style for all types?
![image](https://user-images.githubusercontent.com/30004592/159802789-bb33a3ca-5d92-4f40-b310-c4ce3e5fe65d.png)

**Comment by valentine195** [comment]
If you go into Admonition settings, you can add new custom admonition types there. If you want to override a default, you can create a custom Admonition of the same type (for example, note).

**Comment by Alexnoj** [comment]
> If you go into Admonition settings, you can add new custom admonition types there. If you want to override a default, you can create a custom Admonition of the same type (for example, note).

Yes, I know I can create new custom admonition. But I want to put in each admonition different style: colour, border. Is possible?

**Comment by valentine195** [comment]
You define the color when you create a custom admonition, yes. Or you can use CSS. Each admonition will receive a class `.admonition-<type>` (like `.admonition-note`)

**Comment by Alexnoj** [comment]
> You define the color when you create a custom admonition, yes. Or you can use CSS. Each admonition will receive a class `.admonition-<type>` (like `.admonition-note`)

I will try it. ty
