### ISSUE TITLE
Icons don't appear to work

### ISSUE THREAD

**Issue by BuyMyMojo** [valentine195/obsidian-admonition#232]
I've tried using icons from both Font Awsome and RPG Awsome without success, I've tried using them like this:

```
icon: fa-alien-8bit
```
```
icon: alien-8bit
```
```
icon: ra-hydra
```
```
icon: hydra
```

But the icon doesn't seem to change for me.
I am new to using admonition, am I missing something?

**Comment by valentine195** [comment]
Are you doing this in an Obsidian callout or a code block admonition?

Also:
1. `fa-alien-8bit` is not a free FontAwesome icon. Only the free ones are bundled.
2. You have to download the RPGAwesome icon pack in settings.

**Comment by BuyMyMojo** [comment]
I didn't know about it being a non-free icon. using the `file` icon from FA worked and now RA does too, I might have just needed to restart obsidian. sorry for the trouble!
