### ISSUE TITLE
auto convert old style to new native syntax?

### ISSUE THREAD

**Issue by zeltak** [valentine195/obsidian-admonition#233]
Hi!

first of al thanks for all your amazing work! its my fav plugin ever!

I have hundreds of notes with the old style syntax, ie

```
```ad-abstract
title: Ingredients
4-6 garlic cloves
1 lemon, halved
⅓ cup olive oil
```
```

is there a way to auto/batch convert to new native syntax? is this recommended at all for future proofing?

Also for non obsidian apps which syntax is more standard? 

thx so much

Z

**Comment by valentine195** [comment]
There is a button in admonition settings to convert them. Please make a backup first. 

> Also for non obsidian apps which syntax is more standard?

callouts

**Comment by zeltak** [comment]
thx @valentine195 !

I must be an idiot but for some reason can't find that anywhere in setting

![image](https://user-images.githubusercontent.com/498410/160250201-9327e103-4b54-43aa-b99c-ad0c4128d203.png)


what am I missing  :)

thx!

Z

**Comment by valentine195** [comment]
Are you on Obsidian 0.14+ and Admonitions 8.0+?

**Comment by zeltak** [comment]
ahh I see got it!

thx!
