### ISSUE TITLE
Checkboxes STILL not getting updated in Live Preview

### ISSUE THREAD

**Issue by nousernameavailableanymore** [valentine195/obsidian-admonition#236]
Not sure why issue #166 was closed as checkboxes still do not seem to work in callout boxes.

Was closing the other issue based on previous testing with callout boxes (implying that I may be doing something wrong here) or was this never tested at all?

**Comment by valentine195** [comment]
I am not going to compete with callouts. Code blocks will continue to exist for backward compatibility, but I am not going to spend dev time on them.

if checkboxes do not work in callouts in live preview you need to open a bug report on the forum
