### ISSUE TITLE
Markdown syntax highlighting requiring

### ISSUE THREAD

**Issue by Shuusei04** [valentine195/obsidian-admonition#24]
Would you like to support markdown syntax highlighting in the admonition code block? I think it would be more readable when typing.

![image](https://user-images.githubusercontent.com/52666628/117295896-5eec8200-aeaf-11eb-8ed3-6434a8419f36.png)

**Comment by valentine195** [comment]
Hi, please see #12. I just realized this setting is undocumented, so I'll add it to the documentation.

Thank you for reminding me!

**Comment by Shuusei04** [comment]
Thank you!! I just realized you already have a solution for that.
