### ISSUE TITLE
Code block admonition color override no longer works

### ISSUE THREAD

**Issue by mjschwenne** [valentine195/obsidian-admonition#240]
Hello!

I am using Admonition 9.0.1 with Obsidian 0.14.2 and I'm having issues with code block admonitions not displaying the overridden color.

Take for example the sample given in the README:
````
```ad-note
color: 200, 200, 200

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla.

```
````
RGB (200,200,200) is a silvery gray but when I paste this into Obsidian it renders as 

![image](https://user-images.githubusercontent.com/19698215/161759263-f8aa1e9b-9492-47d1-b243-654ece975820.png)

with the default blue color.

**Comment by kaimackay** [comment]
I have having the same issue, too. I hope this gets fixed; I'm sure it will. Now we wait...

**Comment by Azurewren** [comment]
I have experienced this as well. I discovered that the theme I was using was overriding the admonition css, so you may want to check to see if your current theme is doing that. A simple way is to change back to the default obsidian theme and see if that makes a difference.

**Comment by tingmelvin** [comment]
It seems the problem is that for the changeover to Admonitions 8/9 (can't remember which), `--admonition-color` was kept in the style attributes. Changing that in the inspector to `--callout-color` (which is the same syntax used by Callouts in core Obsidian) makes them render perfectly again.
