### ISSUE TITLE
to-do lists' "done" status is not registered

### ISSUE THREAD

**Issue by jabbalaci** [valentine195/obsidian-admonition#242]
Inside an admonition, I like adding to-do items. When I select the square box

![](https://i.imgur.com/nLXWXxg.png)

the box is checked, meaning the task is done. However, if I switch to another page and come back, the box in unchecked again. If you check a box and look at the source, you get this:

    ```ad-info
    - [ ] buy some bread
    ```
The checked status of a box is not registered.

What I currently do: edit the source code and add an `x` manually. However, clicking on the square would be simpler. It would be great if this issue could be addressed. Thanks.

**Comment by NayzR** [comment]
Can confirm, having the same problem. I don't really know how hard it is to fix, but I concur with you that it would be great if this issue would be addressed

**Comment by valentine195** [comment]
Unfortunately this is difficult to implement and the feature works in native callouts.

this is going to be marked won’t fix. Please use callouts.
