### ISSUE TITLE
Links within admonitions do not appear connected on mind-map

### ISSUE THREAD

**Issue by wkmaiday** [valentine195/obsidian-admonition#244]
Any links within the admonition itself does not end up linking appropriately on the mind map - however the link still works. More of a QoL issue than a utility one.

**Comment by nosas** [comment]
This is a utility issue when locating and updating backlinks. Obsidian has a nice feature where it updates the backlinks when a note's name is changed (called "Automatically update internal links"). The feature does not work for links located within admonitions.

I'll provide an example to clarify the issue: I have a file named "search algorithm properties". This file is linked within admonitions in four other files. There are now three issues:

1. Obsidian shows the file has 0 linked mentions (no backlinks found). Instead, the links are shown in the "Unlinked mentions" section. This issue cascades into the following two problems.
2. Obsidian's "Automatically update internal links" does not work upon changing the filename.
3. Obsidian's graph view does not show links between the five files (as mentioned in OP).

<img width="558" alt="image" src="https://user-images.githubusercontent.com/12710033/196565588-4f501032-14c0-4345-a0f4-5f95b31ad617.png">

**Comment by valentine195** [comment]
This is an unfortunate side effect of Admonitions being a code block. Obsidian does not parse code blocks for its cache, which includes links and tags. 

If you need this function, you can use a native callout - it works in them!

**Comment by nosas** [comment]
Darn, I just read through the Obsidian forums and found the same result: they do not support links in code blocks.
For future reference, usage of native callouts can be found here: https://help.obsidian.md/How+to/Use+callouts

Thanks for the quick response, Valentine 👍
