### ISSUE TITLE
FontAwesome Icons Unavailable

### ISSUE THREAD

**Issue by micwaab** [valentine195/obsidian-admonition#248]
I am using Admonition 9.0.3, Obsidian v0.14.15. I use the Minimal Theme—regularly updated.

Admonition works as expected, except that FontAwesome icons referred to by the name listed on the FontAwesome webpage do not load into Admonition callouts 90% of the time. Instead, the default pencil icon is displayed.

Example of Callout:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/47571490/171270437-213875e8-e470-4fca-9761-7cc3a14ac92a.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/47571490/171270495-cc6ae811-5e52-40fd-a67a-30339161b9c3.png">

(I have copied this ((and other)) icon names directly from FontAwesome. I have also tried removing the dashes between words.)

Any help would be appreciated.

Thanks!

**Comment by valentine195** [comment]
Admonitions is currently using FontAwesome v5.14.3. It looks like this specific icon was added in 6.0.
