### ISSUE TITLE
Autocomplete for callout types

### ISSUE THREAD

**Issue by 0xdevalias** [valentine195/obsidian-admonition#249]
(**Note:** I also created this as a feature request for Obsidian itself, but I figured if it doesn't get added to the core, it could be a nice addition to this plugin: https://forum.obsidian.md/t/autocomplete-for-callout-types/39865)

**Use case or problem**
When using [callouts](https://help.obsidian.md/How+to/Use+callouts) it would be nice if the supported callout types were shown in an autocomplete dropdown list.

**Proposed solution**
As I start typing the callout syntax (eg. `> [!`) an autocomplete dropdown would show up, allowing me to select one of the supported callout types (note, abstract, etc)

**Comment by valentine195** [comment]
This feature has already been implemented in Admonitions. Is it not working for you?

you do have to type 1 character after the !

**Comment by Cito** [comment]
The problem however is that you have to know one letter already, it cannot be used to show a list of *all* possible types. (The autocompletion only suggests types which include the letter you have typed.)

**Comment by 0xdevalias** [comment]
> it cannot be used to show a list of all possible types

If it did, that would definitely be ideal.

**Comment by valentine195** [comment]
@0xdevalias @Cito I just implemented this

**Comment by 0xdevalias** [comment]
@valentine195 Amazing, thanks! :)

**Comment by Cito** [comment]
@valentine195 Awesome, thank you! That was quick!

**Comment by setfed** [comment]
> This feature has already been implemented in Admonitions. Is it not working for you?
> 
> you do have to type 1 character after the !

sorry for asking, can you specify plugin version where it was implemented?
seems that 9.3.3 doesn't have such feature
