### ISSUE TITLE
Quotes in "Admonition Type" field causes rendering issues across all notes

### ISSUE THREAD

**Issue by steven-kraft** [valentine195/obsidian-admonition#25]
I noticed that adding quotations in the "Admonition Type" field when creating a custom admonition type causes an issue with rendering across all notes, even if the note doesn't contain the admonition block. This happens with both double and single quotes. I haven't tested anything else.

![image](https://user-images.githubusercontent.com/4701243/117349271-334ea500-ae79-11eb-876f-5333bda9e010.png)

Random test note in edit mode:
![image](https://user-images.githubusercontent.com/4701243/117349555-83c60280-ae79-11eb-90e7-789fdcb86aa3.png)
Same note when previewing:
![image](https://user-images.githubusercontent.com/4701243/117349704-b4a63780-ae79-11eb-9814-10d5ff2441b6.png)

The behavior is a bit inconsistent. Sometimes the note content will fully render.

Additionally, the console displays this error:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': 'code.language-ad-Exam"ple' is not a valid selector.
    at HTMLDivElement.Element.findAll (app://obsidian.md/app.js:1:265393)
    at app://obsidian.md/app.js:1:858332
    at Function.t.postProcess (app://obsidian.md/app.js:1:933599)
    at t.postProcess (app://obsidian.md/app.js:1:932200)
    at p (app://obsidian.md/app.js:1:847881)
    at e.onRender (app://obsidian.md/app.js:1:848141)
```

**Comment by valentine195** [comment]
This error is generated from Obsidian's end on how they find blocks to send to the plugin's postprocessor. Because I'm generating additional postprocessors dynamically from user input, I'll need to prevent invalid selectors from being saved as new admonition types.

Is there any particular reason you need quotations in an admonition type?

**Comment by steven-kraft** [comment]
I noticed that you can escape the quotes and it gets rid of the error and renders the quote properly.
![image](https://user-images.githubusercontent.com/4701243/117352566-203dd400-ae7d-11eb-8f3d-895ff569dce2.png)
![image](https://user-images.githubusercontent.com/4701243/117352607-2e8bf000-ae7d-11eb-85e9-1fc091fbe9ed.png)


> Is there any particular reason you need quotations in an admonition type?

It doesn't really matter to me, but I was using it to display Japanese "On'Yomi" and "Kun'Yomi" readings, but I imagine there are many situations where an apostrophe would cause an issue.

**Comment by valentine195** [comment]
If you escape any illegal selector characters, it will still work in 4.0.1.
