### ISSUE TITLE
Nesting Admonitions doesn't look quite right

### ISSUE THREAD

**Issue by lillian-who** [valentine195/obsidian-admonition#255]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/20553685/184362317-0e5bdf21-dc0b-427f-942a-9396001839f5.png">

**Comment by lillian-who** [comment]
This only happens in live preview mode.

**Comment by OsoRojo** [comment]
Can confirm.  Thought I had it working until I started building more complex structures, but it does seem that in live preview mode, LP is prematurely terminating the code fence.  Reading mode displays correctly so far as I can tell.

**Comment by OsoRojo** [comment]
And... I just found what my problem was.  I had enabled syntax highlight in code blocks in admonitions plugin in my case, but I did experience this once BEFORE enabling that, and it errored in a similar way.  At least for now, I'm back up and running in both editing and reading mode by disabling syntax highlighting in the plugin.  @lillian-who, maybe give that a shot.  This is also a duplicate of #228

**Comment by bmfe-quant** [comment]
@lillian-who if possible, please give feedback as this helps solidify a solution as being specific to the user’s configuration (@OsoRojo ) vs widely applicable.

**Comment by lillian-who** [comment]
> @lillian-who if possible, please give feedback as this helps solidify a solution as being specific to the user’s configuration (@OsoRojo ) vs widely applicable.

Thanks @OsoRojo , The issue was resolved after disabling syntax highlighting.

**Comment by valentine195** [comment]
What’s up?

Thanks,
Jeremy
