### ISSUE TITLE
More than one paragraph visible in Live Preview mode?

### ISSUE THREAD

**Issue by petzi53** [valentine195/obsidian-admonition#257]
I noticed that a second paragraph (even when using SHIFT-ENTER) is not visible in Live Preview mode as part of the callout. But I can see it in Reading mode. Is this intended, or did I do something wrong? 

In the first case, allowing more than one paragraph to show in Live Preview mode would be very nice.

**Comment by valentine195** [comment]
Is this when using an admonition code block or a call out? Can you show me the source text?

**Comment by petzi53** [comment]
Sorry, I found the solution. I used `<some text>`inside the text passage. But I did not embed the angle brackets with backticks (as I did here). This destroyed the formatting for all the text that came afterward the admonition callout.
