### ISSUE TITLE
Custom admonition doesn't work in pop out window

### ISSUE THREAD

**Issue by ernest67** [valentine195/obsidian-admonition#262]
I have noticed that my custom admonition types do not work in pop out window of obsidian.

When the note is opened in the main obsidian window, my custom admonition type (Notice the grey and orange background) works as intended:
![Screenshot 2022-09-18 at 21 49 32](https://user-images.githubusercontent.com/95947701/190908657-a53754c7-0cf8-4519-87e8-7962b9d96ded.png)

But when the note is opened in a pop out window, my custom admonition type does not apply: (Notice the blue background)
![Screenshot 2022-09-18 at 21 50 27](https://user-images.githubusercontent.com/95947701/190909063-65ead68b-7dc3-4b26-8bcf-88234209d4c9.png)

SYSTEM INFO:
	Obsidian version: v0.16.2
	Installer version: v0.15.8
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 32
		1: Admonition v9.0.5
		2: Minimal Theme Settings v6.0.5
		3: Advanced Tables v0.17.3
		4: Better Word Count v0.8.1
		5: Calendar v1.5.10
		6: Checklist v2.2.8
		7: Dataview v0.5.46
		8: Hider v1.2.1
		9: Hotkeys++ v0.2.7
		10: Icons v0.3.0
		11: Kanban v1.3.20
		12: Mind Map v1.1.0
		13: Outliner v3.0.0
		14: Paste URL into selection v1.7.0
		15: Style Settings v0.4.11
		16: Indentation Guides v1.0.8
		17: Electron Window Tweaker v1.0.8
		18: Sortable v0.2.6
		19: Tag Wrangler v0.5.3
		20: Book Search v0.5.8
		21: Buttons v0.4.16
		22: Icon Folder v1.3.31
		23: Banners v1.3.3
		24: Contextual Typography v2.2.4
		25: Smart Typography v1.0.18
		26: Highlightr v1.2.2
		27: Annotator v0.2.6
		28: Folder Note v0.7.3
		29: File Tree Alternative Plugin v2.2.2
		30: Linter v1.4.4
		31: Templater v1.14.2
		32: QuickAdd v0.5.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

Your help is kindly appreciated. Thank you so much for creating such a useful plug-in!

**Comment by valentine195** [comment]
Oh, interesting, but this makes sense. I'll have to think about how to fix this. Do you have the "CSS Snippet" setting turned on for Admonitions, by chance?

**Comment by ernest67** [comment]
No I did not. Should I try turning it on?

**Comment by valentine195** [comment]
It will probably work if you do

**Comment by ernest67** [comment]
Oh yes it does! Thank you so much!

**Comment by ernest67** [comment]
You are a godsend! Thank you!
