### ISSUE TITLE
Accent in Admonition title does not show up

### ISSUE THREAD

**Issue by AwePhD** [valentine195/obsidian-admonition#280]
Hello,

First of all thanks for this plugin, it's very great. I like to add admonitions to add visual effect to the note. Concise and beautiful. 

## Description of the problem

I want to add accent to my admonition title. I set the title correctly (see below) and the accent is even showing on the preview. Although, in admonition settings and in my notes, I cannot see my accent. 

The example is an admonition type `defi` and its displayed title should **Défis**, I got **Defis** instead :smiling_face_with_tear:  .

My `defi` admonition settings (the 'é' is showing up here):
![image](https://user-images.githubusercontent.com/93187038/210754476-90ddaac8-f106-44a0-a237-37b349959c40.png)

Admonition settings preview (no 'é'):
![image](https://user-images.githubusercontent.com/93187038/210754403-35067631-71b1-4e7b-afe9-374678c1717e.png)

Admonition in a note (no 'é'):
![image](https://user-images.githubusercontent.com/93187038/210752036-dde0b73b-1392-4510-843f-d5c731cb3604.png)

Can you fix it, please? Or maybe I am doing something wrong.

## What I tried

- Disable my theme
- Restart Obsidian
- Reload Obsidian
- Look at #78 , but it's not related

## System info

- Obsidian Version: v1.1.9 (Installer version v0.14.6)
- Plugin version: 9.0.5
- OS: Linux

**Comment by AwePhD** [comment]
I have additional data. If I add any text to the admonition then the error is fixed. But if I reload the note (close / open Obsidian for example), the accent disappear. 


I take a note as exemple, the problem is showing. Then I add a blank line. The *é* is showing. I reload, the problem is back. Then I delete the blank line, the problem is solved: *é* is back. Reload, I still have the problem.

![demo](https://user-images.githubusercontent.com/93187038/210758698-277ab0d3-59d9-47df-b7bb-30a710929f64.mp4)

(I forgot to mute the audio)

**Comment by AwePhD** [comment]
Plus, I have noticed that if I insert an admonition - *your feature* - it will have the accent on the title, no matter the reload. However, if I insert a callout - *Obsidian feature* - there is the problem that I described here.

**Comment by sigrunixia** [comment]
@AwePhD 
Hello! Admonitions applies alpha styling to the color you select to fade it. It also has its own css selector .admonition, which is why you get different results between the two. 

You'll need to choose a darker color, control via custom css, or alter admonitions css directly (See https://github.com/valentine195/obsidian-admonition/blob/master/src/assets/main.css for the css to edit).

**Comment by valentine195** [comment]
@AwePhD  it might be better to open a bug report about this on the obsidian forums. It’s hard to change the underlying callout behavior because of the way it’s baked into the rest of the markdown rendering.
