### ISSUE TITLE
Collapsible Texts inside callout blocks without the title therefore not having the need to add yet another [!callout].

### ISSUE THREAD

**Issue by rotie-alt** [valentine195/obsidian-admonition#283]
My issue is this:

```
>[!note]+
> no.1
> no.2
>>[!note]+ no.3
>> - no.3.1
>> - no.3.2
>---
> no.4
```

![image](https://user-images.githubusercontent.com/122450374/211801282-feb6a25c-7890-48b5-bf15-eef86fde8eff.png)

And honestly, it looks terrible having to use yet another callout every time. 

Can't it just work like this?

```
>[!note]+
> no.1
> no.2
>no.3
 >- no.3.1
 > - no.3.2
> no.4
```

![image](https://user-images.githubusercontent.com/122450374/211802023-763a6021-e532-47fe-9974-902d4b8c047c.png)

**Comment by valentine195** [comment]
This isn’t an issue with the plugin, this is an obsidian feature request. Please open it with the obsidian team.
