### ISSUE TITLE
The tags inside the admoniton is not appearing in the tag search

### ISSUE THREAD

**Issue by anandbhaskaran** [valentine195/obsidian-admonition#285]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/6847984/213686985-18bffa38-0ffa-4d76-8344-ec896293e34b.png">

Steps to reproduce

// Given 
Add the following entry

```ad-quote
title: #Learnings
icon: bolt

#Learnings from a lost sales pitch:

-   Less is more
-   Show solution (not capabilities)
```

// When
Click on the #Learnings tab

// Then
The tags that are inside the admonition is not listed in the search results

**Comment by Saquron** [comment]
Nor are linked documents inside admonitions shown in the 'linked mentions' area. They always show as 'unlinked mentions' even though they are linked.

**Comment by valentine195** [comment]
This is a limitation with Obsidian. Nothing in a code block is added as a metadata item. You have to use native callouts if this is required.
