### ISSUE TITLE
Code block syntax breaks compatibility with mkdocs

### ISSUE THREAD

**Issue by max-uho** [valentine195/obsidian-admonition#3]
Hi, congrats on the plugin.

Do you think it would be possible to integrate the original markdown-extension parsing (!!!) so as to maintain compatibility with mkdocs-material ?

I'm totally incapable of working with TypeScript but the regex is here 

[https://github.com/Python-Markdown/markdown/blob/0e6dc4c4f5dc8d6691eb95549657034f6d9abcb6/markdown/extensions/admonition.py](url)

**Comment by valentine195** [comment]
This would be doable but I'm not sure I want to. The ` ```<language> ` syntax seems to be how the Obsidian devs want features like this to be added, and Obsidian's code block API makes it easy to parse. I'll toy around with it, but I think its unlikely.
