### ISSUE TITLE
can I DIY the block format

### ISSUE THREAD

**Issue by 1912377458** [valentine195/obsidian-admonition#300]
for example, the present block is following:
````
```ad-tip
// something
```
````
However, some website use the following block format:
```
:::tip
// something
:::
```
What should I do to establish a connection with them?

**Comment by valentine195** [comment]
Custom formatting is not supported.

**Comment by solonovamax** [comment]
Would it be possible to have a custom block format be supported?

I'm using obsidian with nextcloud. nextcloud uses the
```
::: [icon]
[content]
:::
```
syntax for admonitions/callouts. I'd like to be able to have in-editor support for that.
