### ISSUE TITLE
[[]]Link not previewable

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-admonition#31]
I mean hover previewed，Can this be fixed?

**Comment by valentine195** [comment]
Can you tell me your plugin version and Obsidian version?

They are previewable for me:

![image](https://user-images.githubusercontent.com/38669521/117972424-227ab500-b2f9-11eb-9835-09ab8142b18f.png)

**Comment by zhl111** [comment]
I upgraded to solve the problem, thanks very much
