### ISSUE TITLE
[Request] Command Prompt / Hotkeys for inserting specific admonition

### ISSUE THREAD

**Issue by Chipandcharge** [valentine195/obsidian-admonition#35]
Hi there, is it possible to have a shortcut for a specific admonition, that basically insert the boilerplate? 

Maybe with a command prompt like ad-note 

‘’’ ad-note
title: 

‘’’

gets inserted.

Maybe there is already a solution to insert these templates. I am happy to configure them once. 

Best regards and thank for the awesome plugin. :)

**Comment by valentine195** [comment]
Shouldn't be too difficult to add commands that could be configured to hotkeys. Let me think about the UX.

For now, if you want to use a plugin to do it, I looked through the community plugins and this one seems like it would work:

https://github.com/konodyuk/obsidian-text-expander

**Comment by valentine195** [comment]
## 4.4.0

-   Added ability to register and unregister commands to insert admonitions into a note. Please see [this section of the ReadMe](https://github.com/valentine195/obsidian-admonition#register-and-unregister-commands)

**Comment by valentine195** [comment]
Hello, I just wanted to follow up and see if the new feature in 4.4.0 is working well for you.

**Comment by Chipandcharge** [comment]
Hey, yes works perfectly. Thanks a million. I just added custom types to overwrite a few standard ones.

I just came across the fact, that deleting a custom type, does not delete the shortcut / command. 

And I need to investigate why the appearance on windows is slightly broken 😂 but I guess that my fault. ;)

**Comment by valentine195** [comment]
> I just came across the fact, that deleting a custom type, does not delete the shortcut / command.

Thanks for letting me know - forgot about this situation. Will be fixed in the next release.

> And I need to investigate why the appearance on windows is slightly broken 😂 but I guess that my fault. ;)

Can you send me a screenshot of what it looks like? Just want to make sure it's not my fault.

Does it look correct if you turn off all custom CSS snippets and return to the default theme?

**Comment by Chipandcharge** [comment]
> Thanks for letting me know - forgot about this situation. Will be fixed in the next release.

No Problem

> Can you send me a screenshot of what it looks like? Just want to make sure it's not my fault.
> Does it look correct if you turn off all custom CSS snippets and return to the default theme?

this is what it looks like with default appearance settings. Somehow the title is missplaced.
![grafik](https://user-images.githubusercontent.com/14878397/120692684-656b1b00-c4a8-11eb-9ee8-ef08ec7db7c2.png)


collapsed:
![grafik](https://user-images.githubusercontent.com/14878397/120692708-6c922900-c4a8-11eb-92f3-85c1cd5519c7.png)

**Comment by valentine195** [comment]
This could be the same thing from #32 - could you please confirm if you downloaded the new Obsidian installer for 0.12.3?

**Comment by Chipandcharge** [comment]
ahh nice. Nope I was still on Installer v0.9.1.

With the new Installer it works smoothly. Thanks a lot for your effort. It's an amazing plugin.

**Comment by valentine195** [comment]
Wonderful. Not sure why being on an old installer causes this issue :shrug:

Glad you like the plugin!
