### ISSUE TITLE
Fix the header metadata resolution for markdown-style nested Admonitions

### ISSUE THREAD

**Issue by mitasov-ra** [valentine195/obsidian-admonition#38]
Here is an example of my note:

<pre lang="markdown">
```ad-note
    My code:
    
    ```xml
    &lt;tag&gt;
        example
    &lt;/tag&gt;
    ```
    
    More info
```
</pre>

### Expected behavior

Admonition renders properly with the code block and two paragraphs.

### Actual behavior

Admonitions renders with the first paragraph and the code block. The second paragraph renders in a separate code block.

Is there any possible solutions fot that?
Maybe same approach as with nested admonitions can fix this?

P.S. I've tried to replace ``` with \<pre> and it helped, but I lost syntax highlighting and horizontal scroll, so this solution is not  good enough

**Comment by mitasov-ra** [comment]
Solved, I've just forgot that Obsidian has `~~~` for code blocks.
```md
~~~ad-note
    My code:
    
    ```xml
    <tag>
        example
    </tag>
    ```
    
    More info
~~~
```

Works just fine!


P.S. But then why you made this `!!! ad-` variant for nesting? Above example works perfectly with Admonitions too.

**Comment by mitasov-ra** [comment]
Here's an example how nesting could be done using pure Markdown.

``````markdown
~~~~~ad-info
title: Info ad
collapse: open
  ~~~~ad-code
  title: code.xml
  collapse: open
  Before bug
    ~~~ad-bug
    title: Some bug
    collapse: close
    Buuuug!
    ~~~
  Between bug and code
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <code></code>
  ```
  After code
  ~~~~
After code block
~~~~~
``````

The result:

![image](https://user-images.githubusercontent.com/29340679/120100187-fdcf6b80-c147-11eb-9a1b-00a557a9dfba.png)

But, as you can see, each new layer of nesting is a bit indented. That's because of improper rendering of `title` and `collapse`.

Below is example of bad header rendering:

``````markdown
~~~~~ad-info
title: Info ad
collapse: open
~~~~ad-code
title: code.xml
collapse: open
Before bug
~~~ad-bug
title: Some bug
collapse: close
Buuuug!
~~~
Between bug and code
```xml
<?xml version="1.0" encoding="UTF-8"?>
<code></code>
```
After code
~~~~
After code block
~~~~~
``````

![image](https://user-images.githubusercontent.com/29340679/120100342-01afbd80-c149-11eb-8aa8-216f0b773d02.png)

As you can see, the last `title` and the last `collapse` overridden the previous ones.

If I switch back to `!!! ad-` for nested admonitions, everything gets completely broken. Also, I can use only 1 to 3 indent size, as 4+ indent renders as code block.

**Comment by mitasov-ra** [comment]
What I propose is to fix how `title` and `collapse` are resolved.

Also, migrating completely to Markdown mechanism of nesting and getting rid of non-standard `!!! ad-` format is also preferrable.

At least, you can just mention this approach in the documentation.

**Comment by valentine195** [comment]
> Solved, I've just forgot that Obsidian has ~~~ for code blocks.

I had no idea this existed. If I did, it would've been much easier to do nested admonitions 😁

**Comment by mitasov-ra** [comment]
@valentine195 Turned out that this syntax, along with ```
````md
Different length of backtick sequence
````
```

Is a part of markdown syntax

And

**Comment by mitasov-ra** [comment]
I'm working with fix atm, and don't quite understand this RegExp

```
/^\b(title|collapse)\b:([\s\S]*?)$/gm
```

1. Why using `\b`
2. Why [\s\S] for match multiple lines if there's `m` flag? Is `title` meant to be multiline?

**Comment by mitasov-ra** [comment]
I think the best solution is to make `title: ***` and `collapse: ***` resolvable only if they are at the very beginning of `src`.

Also, I think that removing all `content: ` is not necessary right now, cause backward compatibility with 0.x versions is overkill and such aggressive move as deleting part of content can be more harmful than profitable.

**Comment by mitasov-ra** [comment]
Just finished fixing `getParametersFromSource()` function so now it resolves 'title' and 'collapse' only at the beginning of admonition.

Also, I've removed code related to `content` parameter

**Comment by valentine195** [comment]
~~~~~~
~~~~~ ad-info
title: Info ad
collapse: open
~~~~ ad-code
title: code.xml
collapse: open
Before bug
~~~ ad-bug
title: Some bug
collapse: close
Buuuug!
~~~
Between bug and code
```xml
<?xml version="1.0" encoding="UTF-8"?>
<code></code>
```
After code
~~~~
After code block
~~~~~
~~~~~~

Just wanted to let future users know:
1. Your example didn't work for me until I placed spaces between the `~~~` and the `ad-<type>` 
2. This example also worked with swapped code block symbols (` ``` ` instead of `~~~`)
