### ISSUE TITLE
New syntax

### ISSUE THREAD

**Issue by SubZeroX** [valentine195/obsidian-admonition#40]
Hey, your plugin is absolutely stunning!

Only one thing will make it better: a diferent syntax.

### The reason

Markdown links won't render, the notes remain as unlinked even thought they´re linked. Of couse this is due to obsidian codes behavior, so it will be cool if we a have a secondary render method to Admonitions so notes can be linked.

### Pratical Example:
The way my note system works is based entirely in "Ad-question" Admonitions. 
![image](https://user-images.githubusercontent.com/13406988/120526351-7ab04e80-c3af-11eb-9aef-254a617474db.png)
But, when a try to add any link inside a Admonition, the note linked remain as unlinked
![image](https://user-images.githubusercontent.com/13406988/120526622-c5ca6180-c3af-11eb-9ca0-550921ce6827.png)

It will be REALLY cool if this notes got linked!

**Comment by valentine195** [comment]
Please see #18, [this section of the ReadMe](https://github.com/valentine195/obsidian-admonition#sync-links-to-metadata-cache) and [this post](https://forum.obsidian.md/t/alternate-syntax-for-codeblock-plugins/18905) on the Obsidian Forum.

Unfortunately this is a difficult problem to solve without an update on Obsidian's side. I attempted to hack it in using undocumented features of the API in version 4.3.0, but it is not perfect (see #36).

Until something is done by the Obsidian devs to make it easier to add internal links to the cache, this is probably the best I can do.

**Comment by SubZeroX** [comment]
I see. Thanks for your quick response!

What about inline Admonitions that renders after ::? 

Can't the plugin identify this and return the rendered Admoniton for that line?

**Comment by valentine195** [comment]
I've toyed around with implementing a custom syntax, but it is difficult to do. The biggest struggle is identifying _what markdown content_ the user wants to be inside the admonition, and intercepting it from being rendered.  An inline tag would work for very simple admonitions, but as they start getting more complex, the markdown blocks that Obsidian's markdown post processor sends to the plugin begin to be split up.
 
I may come back to this and keep trying to implement it, but for now until an update is released on Obsidian's side to enable alternate syntax, the setting added in 4.3.0 is the best I can do.

**Comment by SubZeroX** [comment]
Get it! You right. I don't know how to atract the community attention to this syntax problem. Is something really needed!

**Comment by valentine195** [comment]
Please check out [this](https://github.com/valentine195/obsidian-admonition#non-code-block-admonitions) section of the ReadMe.
