### ISSUE TITLE
Set `collapse: none` when option `Collapsible by default` isnt activated

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#42]
Hey,

after the latest update 5.0.1 my beloved feature isnt working anymore.

I always used the admonition without any title

```
```ad-ai
title: 
##### Was versteht man unter [[Machine Learning]]?  
Some Text
```

and it rendered nicely to this block without the big titlebar.
![image](https://user-images.githubusercontent.com/61796661/120917091-8d779b80-c6ad-11eb-9728-a368d46e6b25.png)

Right now, with even "Collapsible by default" not set, it appears following notification:
![image](https://user-images.githubusercontent.com/61796661/120917125-ac762d80-c6ad-11eb-8662-92b480b323f7.png)
with the titlebar rendered:
![image](https://user-images.githubusercontent.com/61796661/120917138-b861ef80-c6ad-11eb-900a-6f465077591d.png)

Is it possible to set `collapse: none` as default, when the option `Collapsible by default` isnt activated?
If I add `collapse: none` everything works fine, but than i had to edit all my blocks..

**Comment by valentine195** [comment]
Sorry about that - missed this condition when fixing #41. Once I can get on my computer I'll have a fix out.

**Comment by valentine195** [comment]
5.0.2 should fix this, sorry!
