### ISSUE TITLE
request: support render footnote

### ISSUE THREAD

**Issue by Benature** [valentine195/obsidian-admonition#47]
Hi, the footnote in the code block isn't rendered, can this plugin support it? Thank you!

![image](https://user-images.githubusercontent.com/35028647/122217988-86882e80-cee0-11eb-85b6-d794f669646a.png)

**Comment by valentine195** [comment]
I think this is the same problem as #18 and [this forum post](https://forum.obsidian.md/t/alternate-syntax-for-codeblock-plugins/18905). If Obsidian's devs formalize a way to allow this, I will add it, but until then I cannot do anything.
