### ISSUE TITLE
(FQ) Links Rendering in Graph View

### ISSUE THREAD

**Issue by chetachiezikeuzor** [valentine195/obsidian-admonition#49]
Hello! I just want to say, this is one of my favorite and most used plugins!!! Thank you so much for building it ☺️. I did want to ask whether or not it is possible to have links used in admonition blocks render in the graph view? They do so properly in preview mode, but don't show up in the graph. Though, there was a moment where the links DID render (see image below). I still don't know how that happened but that leads me to believe that it could be a possibility. Thank you!

https://user-images.githubusercontent.com/79069364/122677591-96d22f00-d1a8-11eb-815e-2e359a70926d.mp4

![image](https://user-images.githubusercontent.com/79069364/122677653-db5dca80-d1a8-11eb-9043-d970c35ccb00.png)

**Comment by valentine195** [comment]
This is similar to #36, but I'll leave it open to keep me motivated to work on it 😁 

By the way, just wanted to let you know - your (templater?) insert modal is great, but I did add a "register commands" button to the custom admonitions in settings that registers commands to insert admonitions (with and without title). I see you have several admonitions, though, so it could get a little overwhelming :grin: gives me an idea to basically just copy that as a feature, if you don't mind.

I also plan to extend this to allow a user to set an "admonition template", either from the vault or by just typing into a text area, and have that be registered as a command as well.

**Comment by valentine195** [comment]
Hi,

Please see [this](https://github.com/valentine195/obsidian-admonition#non-code-block-admonitions) section of the ReadMe for a workaround for this.
