### ISSUE TITLE
Alternate Syntax with empty Title

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#56]
As i mentioned here : https://github.com/valentine195/obsidian-admonition/issues/42
I would like to use the boxes without the title-header-bar. 

By now it is not possible to set an empty title like this:
```
!!! ad-info 
## Test
- here is some text
--- admonition
```

I also encountered that the content below the Heading does not render properly.

**Comment by valentine195** [comment]
Added in 6.1.0

https://github.com/valentine195/obsidian-admonition#titles-1
