### ISSUE TITLE
Issues with non-codeblock syntax

### ISSUE THREAD

**Issue by jakeoung** [valentine195/obsidian-admonition#57]
I'm excited to find the new option to enable non-codeblock. But it seems quite buggy so far.  For example,

!!! ad-note
title: Hello
weqwe
!!!

which outputs

![image](https://user-images.githubusercontent.com/2376897/123065648-3ee53380-d407-11eb-94b7-d32014d6c851.png)

Also the preview of all other files often becomes empty if I enable this option.

**Comment by erex** [comment]
#### Further issues with non-codeblock option (which I am excited to use--thanks for the modification)

Editing the admonition type causes the preview to break.  See animation below.  If I restart Obsidian after editing, the new edit will work, but that's not the perfect solution

![admonition](https://user-images.githubusercontent.com/330744/123068094-7ead1a80-d409-11eb-8bb0-53dea9932719.gif)

**Comment by valentine195** [comment]
> !!! ad-note
> title: Hello
> weqwe
> !!!

You terminate Admonitions with `--- admonition`. 

> Editing the admonition type causes the preview to break.  See animation below.  If I restart Obsidian after editing, the new edit will work, but that's not the perfect solution. 

I'll add this to the ReadMe caveats, but editing _any_ part of the admonition requires the cache to be cleared to render properly.

**Comment by erex** [comment]
understood, thanks

**Comment by pverflow** [comment]
i have similar issues but without complete close/open it will not render properly. i also dont understand how the header is seperated from the text as puting in an enter doesn't seem to always work. Sometimes its in the header sometimes its completely outside of it. (or maybe its because of the same render issues)

**Comment by valentine195** [comment]
Try a new line between the termination (---) and the paragraph. If that doesn't work, I'll try to recreate your issue when I get a chance. The non-code block Admonitions are rather brittle unfortunately and depend quite a bit on Obsidian deciding to separate blocks out.

As for the backticks, tildes are also a valid code block symbol in markdown.

**Comment by valentine195** [comment]
Closed for inactivity.
