### ISSUE TITLE
How could I have an x-axis scrollbar for admonition when my equation is too long?

### ISSUE THREAD

**Issue by Shuusei04** [valentine195/obsidian-admonition#58]
Here is the example where the equation can not completely render in admonition or, say, it just hides to the corner that I can not see. Would you mind telling me how to solve this problem? Much thanks to you.

<img width="939" alt="CleanShot 2021-06-23 at 21 54 43@2x" src="https://user-images.githubusercontent.com/52666628/123099983-a635ce80-d46d-11eb-83f3-99c545250a51.png">

**Comment by valentine195** [comment]
Added in 6.1.1
