### ISSUE TITLE
Links in admonition blocks not updated on rename

### ISSUE THREAD

**Issue by dolphyfernandes** [valentine195/obsidian-admonition#59]
If you have links (referencing a file, for example) in admonition blocks, and you rename the file, the link does not get updated, resulting in a dead link.

**Comment by valentine195** [comment]
This is because obsidian does not natively out links into its cache. This issue needs to be fixed upstream. 

In the meantime if you need to use links in Admonitions, the only way to get native behavior is to use the non-code block syntax.
