### ISSUE TITLE
"Failed to load plugin" error while enabling the plug-in on Obsidian mobile 0.0.15

### ISSUE THREAD

**Issue by Javelot** [valentine195/obsidian-admonition#6]
Hi,

Trying to enable the plug-in after an installation, while using Obsidian mobile 0.0.15 on an Android 10 device, triggers a "Failed to load plugin" error toast.

![Screenshot_20210406-122910_Obsidian](https://user-images.githubusercontent.com/64957468/113698362-af1bcd00-96d4-11eb-9f6f-0bf0ce0dda42.png)

Does anyone manage to reproduce this problem ?

Thanks for your attention and your time.

**Comment by valentine195** [comment]
Unfortunately I won't be able to do any debugging on this issue because I have neither an Android nor access to the mobile beta.

I'll take a look through the code and see if there's anything that I can see that would cause an issue on mobile, but I can't make any guarantees.

**Comment by lishid** [comment]
The error is "TypeError: Cannot read property 'inspect' of undefined" at 764:51
This seems to come from your polyfill that's compiled for NodeJS instead of browser, which is using the nodejs "util" module.

Maybe just inline the polyfill manually, or just avoid using that function?

**Comment by valentine195** [comment]
Okay, thanks for the help. I switched to the [TC39 proposal polyfill](https://github.com/tc39/proposal-object-from-entries/blob/master/polyfill.js) inline. Could you let me know if v2.0.1 fixes it?

**Comment by lishid** [comment]
Works!

**Comment by valentine195** [comment]
Great, thank you!

**Comment by Javelot** [comment]
@lishid thanks a lot for the stack trace and error analysis.

@valentine195, everything seems a-OK regarding both enabling the plug-in and displaying admnonition boxes.

![Screenshot_20210406-143929_Obsidian](https://user-images.githubusercontent.com/64957468/113712269-36be0780-96e6-11eb-85e9-f4157386bb7b.png)

![Screenshot_20210406-144012_Obsidian](https://user-images.githubusercontent.com/64957468/113712270-37569e00-96e6-11eb-8e4d-11c27f4b53f2.png)

Thank you again to both of you for your help and quick answers !

**Comment by yhoebeke** [comment]
Hello,
It seems that with version 3.0.0, I cannot install the plugin on my android device. When browsing for the admonition plugin, I get a red warning "This plugin does not support your device."
Would you be able to fix this?
Thanks a lot for this beautiful plugin.

**Comment by valentine195** [comment]
Can you try 3.0.1?

**Comment by yhoebeke** [comment]
It works now - thank you !! :)

**Comment by valentine195** [comment]
Great, thanks.
