### ISSUE TITLE
Checkbox click functionality affected by Title and Collapse

### ISSUE THREAD

**Issue by Art-Dei-Tech** [valentine195/obsidian-admonition#61]
Whenever I include collapse and title on top of the admonition content, any checkboxes I add below them act weirdly. In preview mode, the location of the tickbox shifts when I try to click them. For example, I try to click on one checkbox, the one before gets ticked and so on. This issue does not occur if I leave out title and collapse.

```
```ad-actions
title: actions

- [x] This gets ticked instead
- [ ] I clicked on this but it didn't tick
```.

```ad-actions

- [ ] This ticks fine
- [ ] This ticks fine too
```.

**Comment by valentine195** [comment]
This _should_ be fixed in 6.2.0, please test and let me know.

**Comment by Art-Dei-Tech** [comment]
Hi, the ticking position works as hoped! However, when testing it, I found something weird with `collapse`:

Whenever `collapse` is enabled and I try ticking any of the boxes once, the tick registers but the admonition block itself closes. I would need to keep opening the admonition to tick several times.
![Admonition bug](https://user-images.githubusercontent.com/64435179/125952529-f41c7e5d-46c4-462b-bef5-b9dec0360c82.gif)

**Comment by valentine195** [comment]
Please try 6.2.1

**Comment by Art-Dei-Tech** [comment]
Fully fixed! Thanks for the quick hotfix, keep up the great work!
