### ISSUE TITLE
idea: expose icon property for setting inline

### ISSUE THREAD

**Issue by rcox771** [valentine195/obsidian-admonition#62]
Some kinds of admonitions I may only use once or twice.

A nice feature to have would be to allow a user to set the property via setting exposed inline without having to go through a declare a new admonition type 

e.g. -

/```ad-note
icon: ra-triforce

blahblhalbahblahblahbhablah
/```

(prefixing here with /'s, so it doesn't force the render)

**Comment by valentine195** [comment]
Added in 6.2.0, please see [Icon](https://github.com/valentine195/obsidian-admonition#icon) and [Color](https://github.com/valentine195/obsidian-admonition#color)
