### ISSUE TITLE
New Update broke Non-title Syntax again

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#63]
Hey, 

the latest update (6.2.0) broke following issue once again https://github.com/valentine195/obsidian-admonition/issues/56

![image](https://user-images.githubusercontent.com/61796661/125136615-7c3a0880-e10b-11eb-9b88-be353753ec1c.png)
I added the two spaces after the ad-type but it will insert the text into the heading..
![image](https://user-images.githubusercontent.com/61796661/125136630-81975300-e10b-11eb-82eb-37762e711cec.png)

**Comment by TobiasKlosek** [comment]
due to wrong usage of this syntax the issue can be solved. Inserting an line after the heading !!! ad-math works.

**Comment by valentine195** [comment]
Good to know, but I'll still try to work on a fix.
