### ISSUE TITLE
Checkbox preview to markdown problem

### ISSUE THREAD

**Issue by Art-Dei-Tech** [valentine195/obsidian-admonition#65]
Hello! Sorry but I'm facing issues again with the checkbox functionality. The "ticking" works in preview mode but does not change the markdown value like this GIF, and there is no longer a strikethrough like before.  Any edits to checkboxes inside the admonition on preview mode disappears when exiting the note.
![Admonition bug C](https://user-images.githubusercontent.com/64435179/126388051-8bfb0a8b-b9a1-4da6-a453-eb4b5b680234.gif)

**Comment by valentine195** [comment]
Hmm, odd. It was working, right?

**Comment by Art-Dei-Tech** [comment]
Yeah I just noticed now, even on a fresh vault with no other plugins. The markdown was working fine before the `title` `collapse` issue was fixed.

**Comment by valentine195** [comment]
Okay, bad news. Looks like the latest Obsidian update broke this, and it seems to no longer be possible for me to both:

1. Update the checkbox value in the raw markdown
2. Not collapse a collapsible Admonition

6.2.2 restores the checkbox clicking
