### ISSUE TITLE
Export to PDF should de-collapse the collapsed blocks

### ISSUE THREAD

**Issue by dummifiedme** [valentine195/obsidian-admonition#67]
I noticed that while exporting as PDF, the toggle to expand a collapsed block doesn't work (naturally). But could there be a way to expand them while exporting as PDF? Else the data inside these blocks would be hidden :(

Thanks for the plugin! Good work really :)

**Comment by valentine195** [comment]
I don't think I'll be able to do this, but there is a command included with the plugin to expand all Admonitions on a page:

`Admonition: Open Admonitions in Note`
