### ISSUE TITLE
Not working with Obsidian Publish

### ISSUE THREAD

**Issue by user-ce** [valentine195/obsidian-admonition#68]
I've copied CSS styling from `/src/assets/main.css` into my `publish.css`, reset my browser cache and tried making some changes in CSS but I'm not able to get it to work in my webpage.

It would be really great if this plugin can work with Publish feature as well !!

**Comment by valentine195** [comment]
Hi, at the moment the plugin won't work for publish. It has to take the code block and render some HTML before the CSS can do anything and plugins cannot be enabled on publish at the moment.
