### ISSUE TITLE
How can I add multiple code blocks in the same scope?

### ISSUE THREAD

**Issue by Molin-L** [valentine195/obsidian-admonition#69]
For example, one block is for the source code and another one is for the output. But currently I can't use ` ``` ` to close a code block inside of an admonition. It looks like as below:

\``` ad-example

\``` cpp
int main() {
    cout<<"Yo"<<endl;
}

\```bash
Yo

\```

Thanks in advance.

**Comment by valentine195** [comment]
You can nest code blocks indefinitely by adding more backticks. So make the Admonition have 4.

**Comment by Molin-L** [comment]
> You can nest code blocks indefinitely by adding more backticks. So make the Admonition have 4.
> 
> Example
> https://github.com/valentine195/obsidian-admonition#nesting-admonitions

Thanks for your help! The preview looks a little bit complicated. But I think it does solve my problem, thx.
![temp](https://user-images.githubusercontent.com/25400909/128110461-d0eb286b-bd6b-45ff-a769-87ebec5f8c01.png)
