### ISSUE TITLE
Issue with nested Mermaid graph

### ISSUE THREAD

**Issue by ConnorMeyers** [valentine195/obsidian-admonition#70]
Nesting mermaid graphs inside of admonition blocks results in:
![image](https://user-images.githubusercontent.com/14039575/128641073-16904bc8-d93d-497c-ac72-2a6869143b1b.png)

Example:
`````
````ad-note
```mermaid
graph LR
	A --> B
```
````
`````

**Comment by valentine195** [comment]
Okay, I've discovered the source of the bug, but I'm not sure I'm going to be able to fix it. It looks like the mermaid processor is expecting an element to be appended to the body of the window HTML, but for some reason it is not being appended when run through Obsidian's `MarkdownRenderer`. I'll ask on the discord if there's a clean way to fix it.

**Comment by valentine195** [comment]
Figured out a fix. Try 6.2.4
