### ISSUE TITLE
Mermaid fails to render in child-admonition when parent has collapse

### ISSUE THREAD

**Issue by ConnorMeyers** [valentine195/obsidian-admonition#73]
![image](https://user-images.githubusercontent.com/14039575/128741554-9898805f-3819-4233-8c1e-0fc9729a4be8.png)

``````
`````ad-info
collapse:
````ad-note
```mermaid
graph LR
    A --> B
```
````
`````
``````

**Comment by valentine195** [comment]
Not sure I'll be able to solve this one, but I'll give it a shot.

**Comment by valentine195** [comment]
Can't fix, sorry.
