### ISSUE TITLE
Syntax highlighter stops working after using Obsidian/markdown quotes inside admonition

### ISSUE THREAD

**Issue by mikkovedru** [valentine195/obsidian-admonition#74]
## How to reproduce the bug
1. Add 3 test lines inside the admonition:
![image](https://user-images.githubusercontent.com/2521942/129084705-e3b3fbd8-b4b8-4af0-b218-74081bdbc443.png)
2. Use Obsidian/markdown quote feature(`>`) on the second line. BUG: Notice that syntax highlighter stopped working on all the lines even below the quoted one.
![image](https://user-images.githubusercontent.com/2521942/129084882-00ceb899-db30-4dfa-90f5-dae318afd2dc.png)

## Other interesting detail
Putting a code block returns highlighting back to normal.
![image](https://user-images.githubusercontent.com/2521942/129085169-ac3c5d7e-a3d2-4571-9f85-8a99426d0e3f.png)

## Versions
- Obsidian 0.12.10
- Admonition 6.2.2

**Comment by valentine195** [comment]
I think this is the default behavior for the `hypermd` CodeMirror syntax highlighter inside a code block. Not sure I'll be able to fix this unfortunately.

**Comment by mikkovedru** [comment]
@valentine195 
I [reported the bug](https://forum.obsidian.md/t/syntax-highlighter-stops-working-after-using-obsidian-markdown-quotes-inside-admonition/22522/6) to the Obsidian developers, and they answered:
>This is third-party plugin problem. We don’t provide user support for user problems of third party plugins.
>
>It’s up to the third party author to debug the issue and if the issue is due to Obsidian core report to the dev.

Is there something I can do to help this issue to be fixed?

**Comment by valentine195** [comment]
Hi,

By CodeMirror issue, I meant that this behavior occurs in the `hypermd` language highlighter (which is what this plugin uses). 

![image](https://user-images.githubusercontent.com/38669521/132595944-8be8ea09-1253-4d66-ad1e-c609dc4ab3ed.jpeg)

**Comment by mikkovedru** [comment]
@valentine195 
I am utterly confused as to where exactly this bug is and who is responsible.

I [reported this bug to the CodeMirror developers](https://github.com/codemirror/CodeMirror/issues/6775), but they are confused as well:
> marijnh 9 hours ago
>
>I don't know what hypermd is, but there's no support for it anywhere in this library.

**Comment by valentine195** [comment]
I think HyperMD may be this.

https://github.com/laobubu/HyperMD

But yes, I understand that it's annoying. However, HyperMD is the language highlighter that Obsidian uses to highlight its markdown in edit mode. This same behavior happens in that language highlighter, which means there's nothing I can do, because this plugin just uses that language highlighter.

**Comment by mikkovedru** [comment]
I just want to know where this bug is located and want to report it to the appropriate party.

It was confusing, because you mentioned CodeMirror, but the bug had nothing to do with them.

Thank you for pointing me in the right direction. :+1:

**Comment by valentine195** [comment]
> It was confusing, because you mentioned CodeMirror, but the bug had nothing to do with them.

Yep... I didn't realize HyperMD was a separate thing 🤷🏼 Sorry about that!

**Comment by mikkovedru** [comment]
> Yep... I didn't realize HyperMD was a separate thing 🤷🏼 Sorry about that!

No problem, mate. :-)

Thank you for the quick replies and a great job with a lovely plugin that became an essential part of my everyday life! :-)

**Comment by valentine195** [comment]
I'm gonna close this, hopefully HyperMD will fix it.
