### ISSUE TITLE
Issues with unbalanced parentheses 

### ISSUE THREAD

**Issue by bianca-pereira** [valentine195/obsidian-admonition#76]
If the content of the admonition block contains a checkbox item followed by a text with unbalanced parentheses, the block won't load.

if the unbalanced parentheses happen in normal text (no checkbox) it seems to be fine.

![20210813_064706](https://user-images.githubusercontent.com/1379442/129310966-0197705a-b534-4f13-983f-8938dd6af6c8.jpg)
![20210813_064719](https://user-images.githubusercontent.com/1379442/129310971-c21a2472-4e3f-4613-a765-ec0dda9209da.jpg)
![20210813_064806](https://user-images.githubusercontent.com/1379442/129310979-9f8c5ef1-d38a-42e2-9e7f-de619906e213.jpg)
![20210813_064825](https://user-images.githubusercontent.com/1379442/129310986-b7a62eab-edee-4612-8e2d-9545ebc62808.jpg)
![20210813_064848](https://user-images.githubusercontent.com/1379442/129310991-e4c1205e-6edc-4fd1-9fdb-f38a7d0a651c.jpg)
![20210813_064906](https://user-images.githubusercontent.com/1379442/129310995-b3e99016-5756-4670-b423-dbf66689c9f9.jpg)
![20210813_065139](https://user-images.githubusercontent.com/1379442/129311255-39b9a847-2806-4ee9-8017-3cfb33ef7d2e.jpg)
![20210813_065235](https://user-images.githubusercontent.com/1379442/129311248-c2ab2d1a-7429-4356-8918-af01e406d504.jpg)

**Comment by valentine195** [comment]
Should be fixed in 6.2.10 :)

Sorry it took so long!
