### ISSUE TITLE
Font Awesome + RPG Awesome Icon Name Collisions

### ISSUE THREAD

**Issue by mopquill** [valentine195/obsidian-admonition#77]
First off, I want to say thank you for developing such a cool plugin! I know how thankless development of public code can be.

If a an icon name exists for both Font Awesome and RPG Awesome, it would seem RPG Awesome takes precedence -- I assume it's overriding previously-set icon names.

Using "crown" as an example -- as both [Font Awesome](https://fontawesome.com/v5.15/icons/crown?style=solid) and [RPG Awesome](https://nagoshiashumari.github.io/Rpg-Awesome/#:~:text=ra-compass-,ra-crown,-ra-crown-of) have a crown icon -- if I enter `crown` into the "Admonition Icon" field, I see a preview of the Font Awesome crown icon, but selecting it displays the RPG Awesome crown icon.

Screenshot:
![image](https://user-images.githubusercontent.com/1709954/130077850-9e0bc8ca-1af1-47b2-a4ad-f3ee7b06222a.png)

I tried specifying `fa-crown` to see if it would override (which, if not infeasible for reasons specific to this plugin would be my chosen solution), but I do also think Font Awesome should probably take precedence.

The primary solution that I have in mind is that Font Awesome takes precedence, but any icon can be specified directly with e.g. `fa-icon` or `ra-icon`.

**Comment by valentine195** [comment]
Fixed in 6.2.6. Explicitly selecting an icon will use that icon, and entering an icon name without choosing one in the suggester now defaults to Font Awesome.

**Comment by mopquill** [comment]
Wow, you are incredibly fast! Confirmed fixed on my end; had to re-select the icon, but works exactly as expected. Kudos, and thanks again!
