### ISSUE TITLE
[Bug] Editor Syntax hightlighter doesn't work in personnalized admonition type with accented title

### ISSUE THREAD

**Issue by Mara-Li** [valentine195/obsidian-admonition#78]
I remark that if I use a personnalized admonition type with accented title, the syntax hightlighter doesn't work either : 
![image](https://user-images.githubusercontent.com/30244939/130220807-fd338104-788d-4d5a-a3db-fe5a3e6f79d5.png)

**Comment by valentine195** [comment]
Hmm, the language is added to the CodeMirror instance correctly, this may be an upstream bug from CodeMirror. I will see if I can get around it somehow.

**Comment by valentine195** [comment]
Alright, I figured it out. CodeMirror's language matcher is only matching up to the accented part. Not sure I can fix this without doing the same thing, which could definitely cause collisions.

**Comment by valentine195** [comment]
Closed in 6.2.7
