### ISSUE TITLE
non-codeblock admonitions broke in 6.2.8

### ISSUE THREAD

**Issue by EdualcLaiv** [valentine195/obsidian-admonition#80]
Hello.

![image](https://user-images.githubusercontent.com/4270058/130304514-a4581d7b-945e-41da-9917-033bd59ff52f.png)

Settings:
![image](https://user-images.githubusercontent.com/4270058/130304659-be4cca7d-5fde-4869-8213-d0d6bfcaeac0.png)

Markdown:
```markdown
!!! ad-danger

test

--- admonition

```

**Comment by valentine195** [comment]
Think this is fixed now...sorry for the issues!
