### ISSUE TITLE
Ticking checkboxes doesn't work

### ISSUE THREAD

**Issue by 0x4c46** [valentine195/obsidian-admonition#81]
It's the same issue as #9, but I can't reopen this issue.

> Unfortunately it's not possible to tick checkboxes inside admonition enviroment in preview.

Thank you for fixing again.

**Comment by andrea-ww** [comment]
Reporting this is still an issue. Thanks!

**Comment by valentine195** [comment]
Hi, this should be fixed in 6.7.3. Sorry this took so long!
