### ISSUE TITLE
"Insert Admonition" creation not possible without having to use the mouse

### ISSUE THREAD

**Issue by dnngll** [valentine195/obsidian-admonition#87]
# Hello,
and first of all: Thank you for a great plugin!

## Behavior
When creating an Admonition via the command palette, after selecting the type (can be done with the keyboard beautifully, including search, bravo!) it is not possible to either switch to the other options (title, collapsible) or to create it without having to use the mouse. I tried TAB and all possible combinations of MOD-ENTER.

## Feature request
If would be great if you could add keyboard-only creation.

## Sys info
Win10x64 21H1, Obsidian v0.12.12

**Comment by valentine195** [comment]
You should now be able to complete the whole modal with just the keyboard in 6.3.1.

**Comment by dnngll** [comment]
Perfect, thank you : )
