### ISSUE TITLE
Ticking checkboxes doesn't work

### ISSUE THREAD

**Issue by 3nzoFerrari** [valentine195/obsidian-admonition#9]
Very cool plugin to upgrade files visually! Thank you. Unfortunately it's not possible to tick checkboxes inside admonition enviroment in preview.

**Comment by valentine195** [comment]
Okay, this should work now.

Unfortunately Obsidian's MarkdownRenderer doesn't appear to handle this situation if it is not rendering the entire page, so I had to hack it in. This may not work completely the same as native checkboxes.

**Comment by 3nzoFerrari** [comment]
Thanks, but after this update only the first checkbox of Admonition blocks can be ticked.

**Comment by valentine195** [comment]
Okay, I see why. Let me work on it, should have a fix soon.

**Comment by valentine195** [comment]
Can you verify if 3.1.2 fixes it?

**Comment by 3nzoFerrari** [comment]
Yes, it did fix it. Thank you very much for your fast support.

**Comment by valentine195** [comment]
Great, thank you. Let me know if you run into other issues -- like I said, I had to hack in a way to force Obsidian to do this, and it may be a little wonky on edge cases.

**Comment by 0x4c46** [comment]
Hi Valentine, it's broken again but I don't know since which release. 
Thank you for fixing.
