### ISSUE TITLE
[Feature Request] Allow the top and the bottom empty spaces to be removed in admonition blocks

### ISSUE THREAD

**Issue by Obsidian1212** [valentine195/obsidian-admonition#91]
I'm mainly using Obsidian on mobile.

The problem is that phones have a smaller display than computers. And while the empty spaces aren't a big deal when only using single admonitions, they become incredibly space wasting when nested together when I'm trying to make an information block or something.

![Screenshot_20210918-095728713](https://user-images.githubusercontent.com/35908303/133868532-3cfc3c6f-8c90-4b12-aa5f-7f2f16de2b73.jpg)
↑ Like this.

Edit: I just realised there are also empty spaces between these ad- blocks. I wonder if these...

A more personal thing is that sometimes I'm trying to use ad- blocks to replace the `>` because of the same reason.
The `>` blocks in Obsidian is too indented  so they really cannot contain enough text in a line. Using ad- blocks kinda solved that.... just too empty.
![IMG_20210918_100052](https://user-images.githubusercontent.com/35908303/133868639-7d655170-51ac-4e0f-9270-972b08090ab7.jpg)

So I'm like... May I ask for something like `no-padding: top, bottom`? That would be really useful when things are used on mobile.

Thanks so much!

**Comment by valentine195** [comment]
This could be done with a CSS snippet. The app on mobile will have the `.is-mobile` class.

**Comment by valentine195** [comment]
So, I *think* this would work (not at my computer - if it doesn’t, I’ll figure it out in a day or two):

```css
.is-mobile .admonition-content {
    margin: 0px 15px;
}
```

**Comment by Obsidian1212** [comment]
So I did this:
1. Created the folder /vault/.obsidian/snippets
2. Created file mobile-admonitions.css
3. Directly pasted and saved your code into it.
4. Went back to the app and loaded the snippet.
5. Restarted the app.

But nothing have changed. Am I doing something wrong?

**Comment by valentine195** [comment]
It’s possible that it’s not specific enough, so the actual CSS in the plugin is overriding it. I will take a look when I have a chance on my computer!

**Comment by Obsidian1212** [comment]
Thank you so much!

**Comment by Obsidian1212** [comment]
Okay so following your snippet I directly went into the plugins folder and changed the margin number inside the plugin itself.
This time things took effect... It's just that I still need configurations

I think some of the problem lies in the `title: ` thing because the top and bottom space gets notably larger when `title` is set to empty.

So inside the plugin css I modified the margin to `0px`. Nope. Still too empty. I then tried `-20px`...

![IMG_20210918_192801](https://user-images.githubusercontent.com/35908303/133887231-9f43ecc0-d869-4fb2-a15b-d7c5a9e4cd4e.jpg)

As you can see, `title: ` blocks now looked much much better imo, but titled blocks are... kinda broken now.

I'm sorry for this whole kinda weird request, but is this thing fixable?

**Comment by valentine195** [comment]
Yes, all doable via a css snippet. Will post once I have time!

**Comment by Obsidian1212** [comment]
That's a super speedy reply lol, thabk you so much!!

**Comment by valentine195** [comment]
```css
body.is-mobile .admonition {
    margin-top: 0.5rem;
    margin-bottom: 0.5rem;
}

body.is-mobile .admonition-content,
body.is-mobile
    .admonition
    > .admonition-title.no-title
    + .admonition-content-holder {
    margin-top: 0px;
    margin-bottom: 0px;
}
```

This works for me pretty well. Note that the rendered content _inside_ the admonition could also have margins. These would have to be targeted separately.

**Comment by Obsidian1212** [comment]
These worked for me pretty well. Thanks so much!
