### ISSUE TITLE
Improve workflow for keyboard-only use cases?

### ISSUE THREAD

**Issue by mikkovedru** [valentine195/obsidian-admonition#92]
The plugin is not really usable using only the keyboard. Could something be done to improve the situation?

Currently invoking the plugin works fine and allows the use of the keyboard to fill in the Admonition type. This is fine. But after the type is chosen, the keyboard becomes useless:
- Tab does nothing, instead of going from one field to the next. Tab only toggles the first "Admonition type" field.
- Enter does nothing, instead of approving and creating the Admonition.

Interestingly, not choosing the Admonition type allows for the Tab (and local Enter) to work (which means that choosing a type causes a bug: the focus to be lost). But that has issues as well, for example, the inability to see where the focus is, after the initial Type and Title fields. I dare you to try and figure out the correct amount of Tabs to press (and then Enter) to create an Admonition on your first attempt. If you don't press enough Tabs, shit like jumping to the Type selection field happens. If you press too many, the focus leaves the Admonition window and goes in the background documents and interface.

**Comment by valentine195** [comment]
Is this for the Insert Admonition command?

**Comment by mikkovedru** [comment]
Correct.

**Comment by valentine195** [comment]
You should now be able to complete the whole modal with just the keyboard in 6.3.1.

**Comment by mikkovedru** [comment]
It's much much better, thank you! :+1: 

The only 2 additional requests/improvements would be:
1. Is it at all possible to make the modal complete (create) itself if the user presses Enter at any point (focus being in any text field)? I typically want to just select the Type and then create an admonition. Currently, I have to press Tab 4 times.
2. After tabbing to the Create/Insert button, the next Tab goes to the modal-closing cross (cancel). Subsequent Tab presses make the focus travel somewhere in the background document and Obsidian interface. Would it be possible to let the focus cycle (pressing Tab after the last position would make the focus jump on top into the Adminition Type field)?

Thank you for your work!
