### ISSUE TITLE
Insert selection in admonition [Feature request]

### ISSUE THREAD

**Issue by AngelusDomini** [valentine195/obsidian-admonition#93]
I use the Insert Admonition command a lot, and I've noticed that many times, I want to insert text that I've already written in the note into a new admonition rather than create the admonition and then type what I want in it (or copy and paste text I've already written into the new admonition).

In other words, I want to be able to select some text in the note, use the Insert Admonition command and have the selected text inside the new admonition. Currently, if I do this, it just overwrites what I've selected.

**Comment by valentine195** [comment]
Hi, on 6.3.1 the insert command will insert around a selection.
