### ISSUE TITLE
Bug: Cannot select admonition type from the Command Pallette in mobile

### ISSUE THREAD

**Issue by AtlacatlQ** [valentine195/obsidian-admonition#98]
I'm trying to select a type of admonition from command Pallette in mobile but it doesn't allow me to.

**Comment by Tayruh** [comment]
Your video link doesn't work but I was experiencing the same issue. The menu listing all admonitions would pop up  it clicking on the choices wouldn't do anything. I downgraded by to 6.3.1 using the github releases and that didn't work either. However downgrading to 6.3.0 restored functionality, so something got clobbered between then and now.

**Comment by valentine195** [comment]
I believe this is working in 6.3.3 now. Can you test and make sure?

**Comment by Tayruh** [comment]
Hi. I just tested and 6.3.3 is unfortunately still not working for me. It pops up the list but clicking an item in the list only highlights the option. It doesn't close the window and insert the admonition into the text like it should.

**Comment by AtlacatlQ** [comment]
I confirme that too
