### ISSUE TITLE
Separate Type and Title?

### ISSUE THREAD

**Issue by mpql** [valentine195/obsidian-admonition#99]
(This is an enhancement request, not a bug) Would it be feasible -- either optionally as a result of a checkbox, or by configuring some `.json` file -- to set an admonition's title separately from the "Admonition Type" setting?

If I want an admonition like:

````
```ad-my_custom_title
// foo
```
````

...with the title "My Custom Title", I instead get "My_custom_title". I have come across a few use cases where the shorthand "tag" I'd like to type is decidedly different from the title I want to show by default.

Thanks either way!

**Comment by valentine195** [comment]
Not currently possible to have an "alias" for a type, but you _can_ set the title property separately. I guess you'd rather not have to do that every time? :)

**Comment by mopquill** [comment]
Well, I wouldn't expect `ad-My Custom Title` to work, just to specify my own formatting. As far as typing it every time, essentially, yes. I could certainly type the whole thing out each time (which is currently what I'm doing 😅), but it would definitely be a huge improvement to be able to specify.

No obligation, though! Do you accept PRs? I may try my hand at this if I get some time.

**Comment by valentine195** [comment]
> Do you accept PRs? 

Absolutely! I probably won't be able to get to this until next week, but you're more than welcome to take a stab at it. I would greatly appreciate it! :)

**Comment by valentine195** [comment]
This will be in the next release.

**Comment by mpql** [comment]
> This will be in the next release.

Well I hadn't yet finished, so awesome, thanks so much!
